/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import javax.swing.plaf.basic.BasicButtonUI;
import herramientas.TextPrompt;
import javax.swing.JOptionPane;

/**
 *
 * @author jonas
 */
public class AltaProveedor extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    public AltaProveedor()
    {
        initComponents();
        agregarP.setUI(new BasicButtonUI());
        agregarP.setBorder(new RoundedBorder(10));
        atras.setUI(new BasicButtonUI());
        atras.setBorder(new RoundedBorder(10));
        campos();
        erroresInv(0);
    }

    public void campos()
    {
        TextPrompt nombre = new TextPrompt("ABCDE", nombrePrv);
        TextPrompt tel = new TextPrompt("0123456789", telefono);
        TextPrompt dire = new TextPrompt("ABCDE", direccion);
    }

    public void erroresInv(int id)
    {
        switch (id)
        {
            case 1:
                nomProErr.setVisible(false);
                break;
            case 2:
                telefonoErr.setVisible(false);
                break;
            case 3:
                direErr.setVisible(false);
                break;
            case 0:
                telefonoErr.setVisible(false);
                nomProErr.setVisible(false);
                direErr.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombrePrv = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        agregarP = new javax.swing.JButton();
        nomProErr = new javax.swing.JLabel();
        telefonoErr = new javax.swing.JLabel();
        direErr = new javax.swing.JLabel();
        atras = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setText("Alta Proveedor");
        add(bienvenidos);
        bienvenidos.setBounds(270, 80, 260, 44);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Proveedor");
        add(jLabel1);
        jLabel1.setBounds(230, 200, 210, 20);

        nombrePrv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePrv.setToolTipText("");
        nombrePrv.setBorder(null);
        nombrePrv.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nombrePrvFocusGained(evt);
            }
        });
        nombrePrv.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                nombrePrvMouseClicked(evt);
            }
        });
        nombrePrv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombrePrvActionPerformed(evt);
            }
        });
        nombrePrv.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombrePrvKeyTyped(evt);
            }
        });
        add(nombrePrv);
        nombrePrv.setBounds(230, 230, 350, 30);
        add(jSeparator1);
        jSeparator1.setBounds(230, 260, 350, 10);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Telefono");
        add(jLabel9);
        jLabel9.setBounds(230, 290, 230, 20);

        telefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono.setToolTipText("");
        telefono.setBorder(null);
        telefono.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                telefonoFocusGained(evt);
            }
        });
        telefono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefonoKeyTyped(evt);
            }
        });
        add(telefono);
        telefono.setBounds(230, 320, 350, 30);
        add(jSeparator3);
        jSeparator3.setBounds(230, 350, 350, 10);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Dirección");
        add(jLabel11);
        jLabel11.setBounds(230, 380, 200, 20);

        direccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        direccion.setToolTipText("");
        direccion.setBorder(null);
        direccion.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                direccionFocusGained(evt);
            }
        });
        direccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                direccionActionPerformed(evt);
            }
        });
        direccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                direccionKeyTyped(evt);
            }
        });
        add(direccion);
        direccion.setBounds(230, 410, 350, 30);
        add(jSeparator5);
        jSeparator5.setBounds(230, 440, 350, 10);

        agregarP.setBackground(new java.awt.Color(33, 12, 255));
        agregarP.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarP.setForeground(new java.awt.Color(255, 255, 255));
        agregarP.setText("Agregar");
        agregarP.setBorder(null);
        agregarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                agregarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarPMouseExited(evt);
            }
        });
        agregarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarPActionPerformed(evt);
            }
        });
        add(agregarP);
        agregarP.setBounds(320, 570, 140, 50);

        nomProErr.setForeground(new java.awt.Color(255, 0, 0));
        nomProErr.setText("Rellenar Campo");
        add(nomProErr);
        nomProErr.setBounds(230, 260, 350, 16);

        telefonoErr.setForeground(new java.awt.Color(255, 0, 0));
        telefonoErr.setText("Rellenar Campo");
        telefonoErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                telefonoErrFocusGained(evt);
            }
        });
        add(telefonoErr);
        telefonoErr.setBounds(230, 350, 350, 16);

        direErr.setForeground(new java.awt.Color(255, 0, 0));
        direErr.setText("Rellenar Campo");
        direErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                direErrFocusGained(evt);
            }
        });
        add(direErr);
        direErr.setBounds(230, 440, 350, 16);

        atras.setBackground(new java.awt.Color(255, 255, 255));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoAtras.png"))); // NOI18N
        atras.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                atrasMouseExited(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atrasActionPerformed(evt);
            }
        });
        add(atras);
        atras.setBounds(40, 20, 80, 57);
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePrvActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombrePrvActionPerformed
    {//GEN-HEADEREND:event_nombrePrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePrvActionPerformed

    private void nombrePrvKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombrePrvKeyTyped
    {//GEN-HEADEREND:event_nombrePrvKeyTyped
        Validaciones.validaLetra(evt, 20, nombrePrv.getText());
    }//GEN-LAST:event_nombrePrvKeyTyped

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_telefonoActionPerformed
    {//GEN-HEADEREND:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefonoKeyTyped
    {//GEN-HEADEREND:event_telefonoKeyTyped
        Validaciones.validaEntero(evt, 10, telefono.getText());
    }//GEN-LAST:event_telefonoKeyTyped

    private void direccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_direccionActionPerformed
    {//GEN-HEADEREND:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void direccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_direccionKeyTyped
    {//GEN-HEADEREND:event_direccionKeyTyped
        Validaciones.validaAlfaNum(evt, 60, direccion.getText());
    }//GEN-LAST:event_direccionKeyTyped

    private void agregarPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseEntered
    {//GEN-HEADEREND:event_agregarPMouseEntered
        agregarP.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_agregarPMouseEntered

    private void agregarPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseExited
    {//GEN-HEADEREND:event_agregarPMouseExited
        agregarP.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_agregarPMouseExited

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarPActionPerformed
    {//GEN-HEADEREND:event_agregarPActionPerformed
        boolean b = false;
        if (nombrePrv.getText().isEmpty())
        {
            b = true;
            nomProErr.setText("Rellenar Campo");
            nomProErr.setVisible(true);
        }
        if (telefono.getText().isEmpty())
        {
            b = true;
            telefonoErr.setText("Rellenar Campo");
            telefonoErr.setVisible(true);
        }
        if (direccion.getText().isEmpty())
        {
            b = true;
            direErr.setText("Rellenar Campo");
            direErr.setVisible(true);
        }
        if (!b)
        {
            String valores = "DEFAULT, '" + nombrePrv.getText() + "', '" + telefono.getText()
                    + "', '" + direccion.getText() + "'";
            switch (CRUD.create("Proveedor", "", valores, "Proveedor"))
            {
                case 0:
                    JOptionPane.showMessageDialog(null, "Proveedor REGISTRADO");
                    nombrePrv.setText("");
                    telefono.setText("");
                    direccion.setText("");
                    break;
                case 1:
                    
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Proveedor NO REGISTRADO \n"
                            + "El nombre ya se encuentra registrado");
                    break;
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Proveedor NO REGISTRADO");
        }

    }//GEN-LAST:event_agregarPActionPerformed

    private void agregarPMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseClicked
    {//GEN-HEADEREND:event_agregarPMouseClicked

    }//GEN-LAST:event_agregarPMouseClicked

    private void nombrePrvMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombrePrvMouseClicked
    {//GEN-HEADEREND:event_nombrePrvMouseClicked

    }//GEN-LAST:event_nombrePrvMouseClicked

    private void telefonoErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoErrFocusGained
    {//GEN-HEADEREND:event_telefonoErrFocusGained

    }//GEN-LAST:event_telefonoErrFocusGained

    private void direErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direErrFocusGained
    {//GEN-HEADEREND:event_direErrFocusGained

    }//GEN-LAST:event_direErrFocusGained

    private void nombrePrvFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombrePrvFocusGained
    {//GEN-HEADEREND:event_nombrePrvFocusGained
        nomProErr.setVisible(false);
    }//GEN-LAST:event_nombrePrvFocusGained

    private void telefonoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoFocusGained
    {//GEN-HEADEREND:event_telefonoFocusGained
        telefonoErr.setVisible(false);
    }//GEN-LAST:event_telefonoFocusGained

    private void direccionFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direccionFocusGained
    {//GEN-HEADEREND:event_direccionFocusGained
        direErr.setVisible(false);
    }//GEN-LAST:event_direccionFocusGained

    private void atrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atrasActionPerformed
    {//GEN-HEADEREND:event_atrasActionPerformed
        MenuOpciones.pintarOpc(new GestionProveedores());
    }//GEN-LAST:event_atrasActionPerformed

    private void atrasMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseEntered
    {//GEN-HEADEREND:event_atrasMouseEntered
        atras.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_atrasMouseEntered

    private void atrasMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseExited
    {//GEN-HEADEREND:event_atrasMouseExited
        atras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_atrasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarP;
    private javax.swing.JButton atras;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JLabel direErr;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nomProErr;
    private javax.swing.JTextField nombrePrv;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoErr;
    // End of variables declaration//GEN-END:variables
}
