/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicButtonUI;
import herramientas.TextPrompt;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author jonas
 */
public class AltasProductos extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    public AltasProductos()
    {
        initComponents();
        opcProveedor.setUI(Propiedades.createUI(this));
        opcCategoria.setUI(Propiedades.createUI(this));
        agregarP.setUI(new BasicButtonUI());
        agregarP.setBorder(new RoundedBorder(10));
        ResultSet rat = CRUD.read("proveedor", "*", "ORDER BY id");
        cargarComboBox(rat, opcProveedor);
        ResultSet rat2 = CRUD.read("categoria", "*", "ORDER BY id");
        cargarComboBox(rat2, opcCategoria);
        campos();
        erroresInv(0);
        listenersBuscadores();
    }

    public void campos()
    {
        TextPrompt buscProv = new TextPrompt("Ingrese Proveedor", buscaProveedor);
        TextPrompt buscCateg = new TextPrompt("Ingrese Categoria", buscaCategoria);
        TextPrompt nombre = new TextPrompt("ABDCD", nombrePro);
        TextPrompt clave = new TextPrompt("0123456789", claveP);
        TextPrompt unidad = new TextPrompt("UN", unidadM);
        TextPrompt mag = new TextPrompt("12345", magnitudM);
        TextPrompt precio = new TextPrompt("00.00", precioUnitario);
        TextPrompt cant = new TextPrompt("12345", cantidad);
    }

    public void erroresInv(int id)
    {
        switch (id)
        {
            case 1:
                opcCatErr.setVisible(false);
                break;
            case 2:
                claErr.setVisible(false);
                break;
            case 3:
                uniErr.setVisible(false);
                break;
            case 4:
                magErr.setVisible(false);
                break;
            case 5:
                precErr.setVisible(false);
                break;
            case 6:
                cantErr.setVisible(false);
                break;
            case 0:
                proErr.setVisible(false);
                claErr.setVisible(false);
                uniErr.setVisible(false);
                magErr.setVisible(false);
                precErr.setVisible(false);
                cantErr.setVisible(false);
                opcCatErr.setVisible(false);
                opcProvErr.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
//                    jcb.addItem(rat.getString("nombre"));
                    jcb.addItem(rat.getString("id") + ":  " + rat.getString("nombre"));
                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        } else
        {

        }
    }

    // Carga de nuevo los productos a el comboBox
    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione un producto");
        ResultSet rat = CRUD.read(tabla, "*", sentencia);
        cargarComboBox(rat, jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombrePro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        precioUnitario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        unidadM = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        magnitudM = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        opcProveedor = new javax.swing.JComboBox<>();
        opcCategoria = new javax.swing.JComboBox<>();
        agregarP = new javax.swing.JButton();
        claveP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        uniErr = new javax.swing.JLabel();
        opcCatErr = new javax.swing.JLabel();
        claErr = new javax.swing.JLabel();
        magErr = new javax.swing.JLabel();
        cantErr = new javax.swing.JLabel();
        precErr = new javax.swing.JLabel();
        proErr = new javax.swing.JLabel();
        opcProvErr = new javax.swing.JLabel();
        buscaCategoria = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        buscaProveedor = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Alta Producto");
        add(bienvenidos);
        bienvenidos.setBounds(280, 30, 240, 47);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Producto");
        add(jLabel1);
        jLabel1.setBounds(40, 310, 210, 20);

        nombrePro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePro.setToolTipText("");
        nombrePro.setBorder(null);
        nombrePro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombrePro.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nombreProFocusGained(evt);
            }
        });
        nombrePro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                nombreProMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                nombreProMousePressed(evt);
            }
        });
        nombrePro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreProActionPerformed(evt);
            }
        });
        nombrePro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreProKeyTyped(evt);
            }
        });
        add(nombrePro);
        nombrePro.setBounds(40, 340, 350, 30);
        add(jSeparator1);
        jSeparator1.setBounds(40, 370, 350, 10);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Precio Unitario");
        add(jLabel8);
        jLabel8.setBounds(40, 490, 180, 20);

        precioUnitario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precioUnitario.setToolTipText("");
        precioUnitario.setBorder(null);
        precioUnitario.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                precioUnitarioFocusGained(evt);
            }
        });
        precioUnitario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMouseReleased(evt);
            }
        });
        precioUnitario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                precioUnitarioActionPerformed(evt);
            }
        });
        precioUnitario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                precioUnitarioKeyTyped(evt);
            }
        });
        add(precioUnitario);
        precioUnitario.setBounds(40, 520, 350, 30);
        add(jSeparator2);
        jSeparator2.setBounds(40, 550, 350, 10);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Unidad de Medida");
        add(jLabel9);
        jLabel9.setBounds(40, 400, 230, 20);

        unidadM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unidadM.setToolTipText("");
        unidadM.setBorder(null);
        unidadM.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                unidadMFocusGained(evt);
            }
        });
        unidadM.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                unidadMMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                unidadMMousePressed(evt);
            }
        });
        unidadM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                unidadMActionPerformed(evt);
            }
        });
        unidadM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                unidadMKeyTyped(evt);
            }
        });
        add(unidadM);
        unidadM.setBounds(40, 430, 350, 30);
        add(jSeparator3);
        jSeparator3.setBounds(40, 460, 350, 10);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Magnitud de Medida");
        add(jLabel10);
        jLabel10.setBounds(420, 400, 200, 20);

        magnitudM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        magnitudM.setToolTipText("");
        magnitudM.setBorder(null);
        magnitudM.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                magnitudMFocusGained(evt);
            }
        });
        magnitudM.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                magnitudMMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                magnitudMMousePressed(evt);
            }
        });
        magnitudM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                magnitudMActionPerformed(evt);
            }
        });
        magnitudM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                magnitudMKeyTyped(evt);
            }
        });
        add(magnitudM);
        magnitudM.setBounds(420, 430, 350, 30);
        add(jSeparator4);
        jSeparator4.setBounds(420, 460, 350, 10);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Cantidad (Stoks)");
        add(jLabel11);
        jLabel11.setBounds(420, 490, 200, 20);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidad.setToolTipText("");
        cantidad.setBorder(null);
        cantidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                cantidadFocusGained(evt);
            }
        });
        cantidad.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cantidadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                cantidadMousePressed(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cantidadKeyTyped(evt);
            }
        });
        add(cantidad);
        cantidad.setBounds(420, 520, 350, 30);
        add(jSeparator5);
        jSeparator5.setBounds(420, 550, 350, 10);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setText("Categoria");
        add(jLabel12);
        jLabel12.setBounds(410, 130, 130, 24);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Proveedor");
        add(jLabel13);
        jLabel13.setBounds(30, 130, 130, 24);

        opcProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un proveedor" }));
        opcProveedor.setToolTipText("");
        opcProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcProveedor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcProveedorFocusGained(evt);
            }
        });
        opcProveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcProveedorActionPerformed(evt);
            }
        });
        add(opcProveedor);
        opcProveedor.setBounds(30, 210, 350, 28);

        opcCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoria" }));
        opcCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcCategoria.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcCategoriaFocusGained(evt);
            }
        });
        opcCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcCategoriaActionPerformed(evt);
            }
        });
        add(opcCategoria);
        opcCategoria.setBounds(410, 210, 350, 28);

        agregarP.setBackground(new java.awt.Color(33, 12, 255));
        agregarP.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarP.setForeground(new java.awt.Color(255, 255, 255));
        agregarP.setText("Agregar");
        agregarP.setBorder(null);
        agregarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                agregarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarPMouseExited(evt);
            }
        });
        agregarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarPActionPerformed(evt);
            }
        });
        add(agregarP);
        agregarP.setBounds(330, 630, 140, 50);

        claveP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        claveP.setToolTipText("");
        claveP.setBorder(null);
        claveP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                clavePFocusGained(evt);
            }
        });
        claveP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                clavePMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                clavePMousePressed(evt);
            }
        });
        claveP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clavePActionPerformed(evt);
            }
        });
        claveP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                clavePKeyTyped(evt);
            }
        });
        add(claveP);
        claveP.setBounds(420, 340, 350, 30);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Clave del Producto");
        add(jLabel2);
        jLabel2.setBounds(420, 310, 210, 20);
        add(jSeparator6);
        jSeparator6.setBounds(420, 370, 350, 10);

        uniErr.setForeground(new java.awt.Color(255, 0, 0));
        uniErr.setText("Rellenar Campo");
        add(uniErr);
        uniErr.setBounds(40, 460, 350, 16);

        opcCatErr.setForeground(new java.awt.Color(255, 0, 0));
        opcCatErr.setText("Seleccionar opción");
        add(opcCatErr);
        opcCatErr.setBounds(410, 240, 350, 16);

        claErr.setForeground(new java.awt.Color(255, 0, 0));
        claErr.setText("Rellenar Campo");
        add(claErr);
        claErr.setBounds(420, 370, 350, 16);

        magErr.setForeground(new java.awt.Color(255, 0, 0));
        magErr.setText("Rellenar Campo");
        add(magErr);
        magErr.setBounds(420, 460, 350, 16);

        cantErr.setForeground(new java.awt.Color(255, 0, 0));
        cantErr.setText("Rellenar Campo");
        add(cantErr);
        cantErr.setBounds(420, 550, 350, 16);

        precErr.setForeground(new java.awt.Color(255, 0, 0));
        precErr.setText("Rellenar Campo");
        add(precErr);
        precErr.setBounds(40, 550, 350, 16);

        proErr.setForeground(new java.awt.Color(255, 0, 0));
        proErr.setText("Rellenar Campo");
        proErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                proErrFocusGained(evt);
            }
        });
        add(proErr);
        proErr.setBounds(40, 370, 350, 16);

        opcProvErr.setForeground(new java.awt.Color(255, 0, 0));
        opcProvErr.setText("Seleccionar opción");
        add(opcProvErr);
        opcProvErr.setBounds(30, 240, 350, 16);

        buscaCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscaCategoria.setToolTipText("");
        buscaCategoria.setBorder(null);
        buscaCategoria.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                buscaCategoriaFocusGained(evt);
            }
        });
        buscaCategoria.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buscaCategoriaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                buscaCategoriaMousePressed(evt);
            }
        });
        buscaCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaCategoriaActionPerformed(evt);
            }
        });
        buscaCategoria.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                buscaCategoriaKeyTyped(evt);
            }
        });
        add(buscaCategoria);
        buscaCategoria.setBounds(410, 160, 350, 30);
        add(jSeparator7);
        jSeparator7.setBounds(410, 190, 350, 10);

        buscaProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscaProveedor.setToolTipText("");
        buscaProveedor.setBorder(null);
        buscaProveedor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                buscaProveedorFocusGained(evt);
            }
        });
        buscaProveedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buscaProveedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                buscaProveedorMousePressed(evt);
            }
        });
        buscaProveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaProveedorActionPerformed(evt);
            }
        });
        buscaProveedor.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                buscaProveedorPropertyChange(evt);
            }
        });
        buscaProveedor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                buscaProveedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                buscaProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                buscaProveedorKeyTyped(evt);
            }
        });
        add(buscaProveedor);
        buscaProveedor.setBounds(30, 160, 350, 30);
        add(jSeparator8);
        jSeparator8.setBounds(30, 190, 350, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreProActionPerformed
    {//GEN-HEADEREND:event_nombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProActionPerformed

    private void nombreProKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreProKeyTyped
    {//GEN-HEADEREND:event_nombreProKeyTyped
        Validaciones.va(evt, 30, nombrePro.getText());
    }//GEN-LAST:event_nombreProKeyTyped

    private void precioUnitarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_precioUnitarioActionPerformed
    {//GEN-HEADEREND:event_precioUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioUnitarioActionPerformed

    private void precioUnitarioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioUnitarioKeyTyped
    {//GEN-HEADEREND:event_precioUnitarioKeyTyped
        Validaciones.validaPrecios(evt, 10, precioUnitario.getText());
    }//GEN-LAST:event_precioUnitarioKeyTyped

    private void unidadMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_unidadMActionPerformed
    {//GEN-HEADEREND:event_unidadMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadMActionPerformed

    private void unidadMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_unidadMKeyTyped
    {//GEN-HEADEREND:event_unidadMKeyTyped
        Validaciones.va(evt, 2, unidadM.getText());
    }//GEN-LAST:event_unidadMKeyTyped

    private void magnitudMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_magnitudMActionPerformed
    {//GEN-HEADEREND:event_magnitudMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magnitudMActionPerformed

    private void magnitudMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_magnitudMKeyTyped
    {//GEN-HEADEREND:event_magnitudMKeyTyped
        Validaciones.validaEntero(evt, 5, magnitudM.getText());
    }//GEN-LAST:event_magnitudMKeyTyped

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cantidadActionPerformed
    {//GEN-HEADEREND:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cantidadKeyTyped
    {//GEN-HEADEREND:event_cantidadKeyTyped
        Validaciones.validaEntero(evt, 5, cantidad.getText());
    }//GEN-LAST:event_cantidadKeyTyped

    private void opcProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcProveedorActionPerformed
    {//GEN-HEADEREND:event_opcProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcProveedorActionPerformed

    private void opcCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcCategoriaActionPerformed
    {//GEN-HEADEREND:event_opcCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcCategoriaActionPerformed

    private void agregarPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseEntered
    {//GEN-HEADEREND:event_agregarPMouseEntered
        agregarP.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_agregarPMouseEntered

    private void agregarPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseExited
    {//GEN-HEADEREND:event_agregarPMouseExited
        agregarP.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_agregarPMouseExited

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarPActionPerformed
    {//GEN-HEADEREND:event_agregarPActionPerformed
        int opc = 0;
        if (opcProveedor.getItemCount() == 1)
        {
            opc = 1;
        }
        if (opcCategoria.getItemCount() == 1)
        {
            if (opc == 1)
            {
                opc = 3;
            } else
            {
                opc = 2;
            }
        }
        if (opc == 0)
        {
            boolean b = false;
            if (nombrePro.getText().isEmpty())
            {
                b = true;
                proErr.setText("Rellenar Campo");
                proErr.setVisible(true);
            }
            if (claveP.getText().isEmpty())
            {
                b = true;
                claErr.setText("Rellenar Campo");
                claErr.setVisible(true);
            }
            if (unidadM.getText().isEmpty())
            {
                b = true;
                uniErr.setText("Rellenar Campo");
                uniErr.setVisible(true);
            }
            if (magnitudM.getText().isEmpty())
            {
                b = true;
                magErr.setText("Rellenar Campo");
                magErr.setVisible(true);
            }
            if (precioUnitario.getText().isEmpty())
            {
                b = true;
                precErr.setText("Rellenar Campo");
                precErr.setVisible(true);
            }
            if (cantidad.getText().isEmpty())
            {
                b = true;
                cantErr.setText("Rellenar Campo");
                cantErr.setVisible(true);
            }
            if (opcCategoria.getSelectedIndex() == 0)
            {
                b = true;
                opcCatErr.setVisible(true);
            }
            if (opcProveedor.getSelectedIndex() == 0)
            {
                b = true;
                opcProvErr.setVisible(true);
            }
            if (!b)
            {
                String valores = claveP.getText() + ", '" + nombrePro.getText() + "', '" + unidadM.getText()
                        + "', " + magnitudM.getText() + ", " + precioUnitario.getText() + " ,"
                        + cantidad.getText() + ", " + (opcProveedor.getSelectedItem().toString().split(":")[0]
                        + ", " + (opcCategoria.getSelectedItem().toString().split(":")[0]));
                int c = CRUD.create("Producto", "", valores, "Producto");
                switch (c)
                {
                    case 0:
                        JOptionPane.showMessageDialog(null, "Producto REGISTRADO");
                        nombrePro.setText("");
                        claveP.setText("");
                        unidadM.setText("");
                        magnitudM.setText("");
                        precioUnitario.setText("");
                        cantidad.setText("");
                        opcProveedor.setSelectedIndex(0);
                        opcCategoria.setSelectedIndex(0);
                        buscaProveedor.setText("");
                        buscaCategoria.setText("");
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(null, "Producto NO REGISTRADO \n La clave ya se encuentra en el sistema");
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(null, "Producto NO REGISTRADO \n Los datos del producto ya se encuentran en el sistema"+
                                "\n (Nombre, Proveedor, Unidad, Magnitud)");
                        break;
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "Producto NO REGISTRADO");
            }
        } else
        {
            if (opc == 3)
            {
                JOptionPane.showMessageDialog(null, "NO datos CATEGORIAS/PROVEEDORES");
            } else if (opc == 2)
            {
                JOptionPane.showMessageDialog(null, "NO datos de CATEGORIAS");
                opcCatErr.setText("No datos");
                opcCatErr.setVisible(true);
            } else
            {
                JOptionPane.showMessageDialog(null, "NO datos de PROVEEDORES");
                opcProvErr.setText("No datos");
                opcProvErr.setVisible(true);
            }
        }
    }//GEN-LAST:event_agregarPActionPerformed

    private void agregarPMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseClicked
    {//GEN-HEADEREND:event_agregarPMouseClicked

    }//GEN-LAST:event_agregarPMouseClicked

    private void nombreProMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombreProMouseClicked
    {//GEN-HEADEREND:event_nombreProMouseClicked

    }//GEN-LAST:event_nombreProMouseClicked

    private void clavePMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clavePMouseClicked
    {//GEN-HEADEREND:event_clavePMouseClicked

    }//GEN-LAST:event_clavePMouseClicked

    private void clavePActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clavePActionPerformed
    {//GEN-HEADEREND:event_clavePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clavePActionPerformed

    private void clavePKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_clavePKeyTyped
    {//GEN-HEADEREND:event_clavePKeyTyped
        Validaciones.validaEntero(evt, 13, claveP.getText());
    }//GEN-LAST:event_clavePKeyTyped

    private void unidadMMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_unidadMMouseClicked
    {//GEN-HEADEREND:event_unidadMMouseClicked

    }//GEN-LAST:event_unidadMMouseClicked

    private void magnitudMMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_magnitudMMouseClicked
    {//GEN-HEADEREND:event_magnitudMMouseClicked

    }//GEN-LAST:event_magnitudMMouseClicked

    private void precioUnitarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMouseClicked
    {//GEN-HEADEREND:event_precioUnitarioMouseClicked

    }//GEN-LAST:event_precioUnitarioMouseClicked

    private void cantidadMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cantidadMouseClicked
    {//GEN-HEADEREND:event_cantidadMouseClicked

    }//GEN-LAST:event_cantidadMouseClicked

    private void nombreProMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombreProMousePressed
    {//GEN-HEADEREND:event_nombreProMousePressed

    }//GEN-LAST:event_nombreProMousePressed

    private void clavePMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clavePMousePressed
    {//GEN-HEADEREND:event_clavePMousePressed

    }//GEN-LAST:event_clavePMousePressed

    private void unidadMMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_unidadMMousePressed
    {//GEN-HEADEREND:event_unidadMMousePressed

    }//GEN-LAST:event_unidadMMousePressed

    private void magnitudMMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_magnitudMMousePressed
    {//GEN-HEADEREND:event_magnitudMMousePressed

    }//GEN-LAST:event_magnitudMMousePressed

    private void precioUnitarioMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMouseReleased
    {//GEN-HEADEREND:event_precioUnitarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_precioUnitarioMouseReleased

    private void precioUnitarioMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMousePressed
    {//GEN-HEADEREND:event_precioUnitarioMousePressed

    }//GEN-LAST:event_precioUnitarioMousePressed

    private void cantidadMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cantidadMousePressed
    {//GEN-HEADEREND:event_cantidadMousePressed

    }//GEN-LAST:event_cantidadMousePressed

    private void nombreProFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombreProFocusGained
    {//GEN-HEADEREND:event_nombreProFocusGained
        proErr.setVisible(false);
    }//GEN-LAST:event_nombreProFocusGained

    private void clavePFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_clavePFocusGained
    {//GEN-HEADEREND:event_clavePFocusGained
        claErr.setVisible(false);
    }//GEN-LAST:event_clavePFocusGained

    private void unidadMFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_unidadMFocusGained
    {//GEN-HEADEREND:event_unidadMFocusGained
        uniErr.setVisible(false);
    }//GEN-LAST:event_unidadMFocusGained

    private void magnitudMFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_magnitudMFocusGained
    {//GEN-HEADEREND:event_magnitudMFocusGained
        magErr.setVisible(false);
    }//GEN-LAST:event_magnitudMFocusGained

    private void precioUnitarioFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_precioUnitarioFocusGained
    {//GEN-HEADEREND:event_precioUnitarioFocusGained
        precErr.setVisible(false);
    }//GEN-LAST:event_precioUnitarioFocusGained

    private void cantidadFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_cantidadFocusGained
    {//GEN-HEADEREND:event_cantidadFocusGained
        cantErr.setVisible(false);
    }//GEN-LAST:event_cantidadFocusGained

    private void opcProveedorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcProveedorFocusGained
    {//GEN-HEADEREND:event_opcProveedorFocusGained
        opcProvErr.setVisible(false);
    }//GEN-LAST:event_opcProveedorFocusGained

    private void opcCategoriaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcCategoriaFocusGained
    {//GEN-HEADEREND:event_opcCategoriaFocusGained
        opcCatErr.setVisible(false);
    }//GEN-LAST:event_opcCategoriaFocusGained

    private void proErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proErrFocusGained
    {//GEN-HEADEREND:event_proErrFocusGained

    }//GEN-LAST:event_proErrFocusGained

    private void buscaCategoriaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buscaCategoriaFocusGained
    {//GEN-HEADEREND:event_buscaCategoriaFocusGained
        opcCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_buscaCategoriaFocusGained

    private void buscaCategoriaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaCategoriaMouseClicked
    {//GEN-HEADEREND:event_buscaCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaMouseClicked

    private void buscaCategoriaMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaCategoriaMousePressed
    {//GEN-HEADEREND:event_buscaCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaMousePressed

    private void buscaCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaCategoriaActionPerformed
    {//GEN-HEADEREND:event_buscaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaActionPerformed

    private void buscaCategoriaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaCategoriaKeyTyped
    {//GEN-HEADEREND:event_buscaCategoriaKeyTyped
        Validaciones.validaLetra(evt, 20, buscaCategoria.getText());
    }//GEN-LAST:event_buscaCategoriaKeyTyped

    private void buscaProveedorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buscaProveedorFocusGained
    {//GEN-HEADEREND:event_buscaProveedorFocusGained
       opcProveedor.setSelectedIndex(0);
    }//GEN-LAST:event_buscaProveedorFocusGained

    private void buscaProveedorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaProveedorMouseClicked
    {//GEN-HEADEREND:event_buscaProveedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProveedorMouseClicked

    private void buscaProveedorMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaProveedorMousePressed
    {//GEN-HEADEREND:event_buscaProveedorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProveedorMousePressed

    private void buscaProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaProveedorActionPerformed
    {//GEN-HEADEREND:event_buscaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProveedorActionPerformed

    private void buscaProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaProveedorKeyTyped
    {//GEN-HEADEREND:event_buscaProveedorKeyTyped
        Validaciones.va(evt, 20, buscaProveedor.getText());

    }//GEN-LAST:event_buscaProveedorKeyTyped

    private void buscaProveedorKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaProveedorKeyPressed
    {//GEN-HEADEREND:event_buscaProveedorKeyPressed
        System.out.println(buscaProveedor.getText());
    }//GEN-LAST:event_buscaProveedorKeyPressed

    private void buscaProveedorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaProveedorKeyReleased
    {//GEN-HEADEREND:event_buscaProveedorKeyReleased

    }//GEN-LAST:event_buscaProveedorKeyReleased

    private void buscaProveedorPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_buscaProveedorPropertyChange
    {//GEN-HEADEREND:event_buscaProveedorPropertyChange

    }//GEN-LAST:event_buscaProveedorPropertyChange

    public void listenersBuscadores()
    {
        buscaProveedor.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                // Acción cuando se inserta texto
                if (buscaProveedor.getText().isEmpty())
                {
                    consultaCombo(opcProveedor, "Proveedor", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaProveedor.getText() + "%'";
                    System.out.println(sentencia);
                    consultaCombo(opcProveedor, "Proveedor", sentencia);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e)
            {
                // Acción cuando se elimina texto
                if (buscaProveedor.getText().isEmpty())
                {
                    consultaCombo(opcProveedor, "Proveedor", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaProveedor.getText() + "%'";
                    System.out.println(sentencia);
                    consultaCombo(opcProveedor, "Proveedor", sentencia);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e)
            {

            }
        });
        buscaCategoria.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                // Acción cuando se inserta texto
                if (buscaCategoria.getText().isEmpty())
                {
                    consultaCombo(opcCategoria, "Categoria", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaCategoria.getText() + "%'";
                    consultaCombo(opcCategoria, "Categoria", sentencia);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e)
            {
                // Acción cuando se elimina texto
                if (buscaCategoria.getText().isEmpty())
                {
                    consultaCombo(opcCategoria, "Categoria", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaCategoria.getText() + "%'";
                    consultaCombo(opcCategoria, "Categoria", sentencia);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e)
            {

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarP;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JTextField buscaCategoria;
    private javax.swing.JTextField buscaProveedor;
    private javax.swing.JLabel cantErr;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel claErr;
    private javax.swing.JTextField claveP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel magErr;
    private javax.swing.JTextField magnitudM;
    private javax.swing.JTextField nombrePro;
    private javax.swing.JLabel opcCatErr;
    private javax.swing.JComboBox<String> opcCategoria;
    private javax.swing.JLabel opcProvErr;
    private javax.swing.JComboBox<String> opcProveedor;
    private javax.swing.JLabel precErr;
    private javax.swing.JTextField precioUnitario;
    private javax.swing.JLabel proErr;
    private javax.swing.JLabel uniErr;
    private javax.swing.JTextField unidadM;
    // End of variables declaration//GEN-END:variables
}
