/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import java.awt.Color;
import java.awt.Font;
import java.awt.Label;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonas
 */
public class ConsultaPGeneral extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    DefaultTableModel m2 = new DefaultTableModel();

    public ConsultaPGeneral()
    {
        initComponents();
        jScrollPane1.setVisible(true);
        jTable1.setRowHeight(32);
        m2 = new DefaultTableModel();
        String c2[] =
        {
            "Clave", "Nombre", "Precio", "Cantidad", "Magnitud", "Unidad", "Proveedor", "Categoria"
        };
        m2.setColumnIdentifiers(c2);
        jTable1.setModel(m2);
        try
        {
            ResultSet rat = CRUD.read("producto", "*", "");
            while (rat.next())
            {
                ResultSet ratProv = CRUD.read("proveedor", "*", "WHERE id = " + rat.getString("id_Proveedor"));
                ratProv.next();
                ResultSet ratCat = CRUD.read("categoria", "*", "WHERE id = " + rat.getString("id_Categoria"));
                ratCat.next();
                String f[] =
                {
                    rat.getString("id"), rat.getString("nombre"), rat.getString("precio"),
                    rat.getString("cantidad"), rat.getString("magnitudMed"), rat.getString("unidadMed"),
                    ratProv.getString("nombre"), ratCat.getString("nombre")
                };
                m2.addRow(f);

            }

        } catch (Exception e)
        {
            System.out.println(e.toString());
            System.out.println("asdasaaaaaaaaaaaaa");
        }
        jTable1.setEnabled(false);
        if (!(jTable1.getRowCount() >= 1))
        {
            jPanel1.remove(jScrollPane1);
            jPanel1.setBackground(new Color(204, 204, 204));
            JLabel l = new JLabel();
            l.setText("No hay Productos");
            l.setBounds(0, 0, 680, 280);
            l.setVerticalAlignment(0);
            l.setHorizontalAlignment(0);
            Font f = new Font(this.getFont().getName(), 3, 48);
            l.setFont(f);
            jPanel1.add(l);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 680, 370);

        add(jPanel1);
        jPanel1.setBounds(60, 100, 680, 370);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
