/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.TextPrompt;
import herramientas.Validaciones;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ConsultarVPorProd extends javax.swing.JPanel
{

    /**
     * Creates new form AgregarCategoria
     */
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);
    DefaultTableModel m2 = new DefaultTableModel();
    private Set<String> fechasExistentes = new HashSet<>();

    public ConsultarVPorProd()
    {
        initComponents();
        opcFecha.setUI(Propiedades.createUI(this));
        consultaCombo(opcFecha, "producto", "");
        jScrollPane1.setVisible(false);
    }

    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione un producto");
        ResultSet rat = CRUD.read(tabla, "*", sentencia);
        cargarComboBox(rat, jb);
    }

    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
                    String fecha = rat.getString("nombre");
                    if (!fechasExistentes.contains(fecha))
                    {
                        jcb.addItem(fecha);
                        fechasExistentes.add(fecha);
                    }
                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        opcFecha = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 660, 370);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 660, 370));

        opcFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una fecha" }));
        opcFecha.setToolTipText("");
        opcFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcFecha.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcFechaFocusGained(evt);
            }
        });
        opcFecha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcFechaActionPerformed(evt);
            }
        });
        add(opcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Producto");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void opcFechaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcFechaFocusGained
    {//GEN-HEADEREND:event_opcFechaFocusGained

    }//GEN-LAST:event_opcFechaFocusGained

    private void opcFechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcFechaActionPerformed
    {//GEN-HEADEREND:event_opcFechaActionPerformed
        if (opcFecha.getSelectedIndex() != 0 && opcFecha.getItemCount() > 1)
        {
            jScrollPane1.setVisible(true);
            jTable1.setRowHeight(32);
            m2 = new DefaultTableModel();
            String c2[] =
            {
                "Fecha de vendido", "Nombre Producto", "Cantidad", "Total"
            };
            m2.setColumnIdentifiers(c2);
            jTable1.setModel(m2);
            try
            {
                String sentencia = opcFecha.getSelectedItem().toString();
                ResultSet rat = CRUD.consultarProducto(sentencia);
                while (rat.next())
                {
                    String f[] =
                    {
                        rat.getString("fecha_vendida"), rat.getString("nombre_producto"),
                        rat.getString("cantidad"), rat.getString("total")
                    };
                    m2.addRow(f);

                }
            } catch (Exception e)
            {
                System.out.println("asdasaaaaaaaaaaaaa");
            }
            jTable1.setEnabled(false);
        } else
        {
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_opcFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> opcFecha;
    // End of variables declaration//GEN-END:variables
}
