/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.TextPrompt;
import herramientas.Validaciones;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ConsultarVPorProdVenta extends javax.swing.JPanel
{

    /**
     * Creates new form AgregarCategoria
     */
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);
    DefaultTableModel m2 = new DefaultTableModel();

    public ConsultarVPorProdVenta()
    {
        initComponents();
        tickErr.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione una Venta");
        ResultSet rat = CRUD.read(tabla, "*", sentencia);
        cargarComboBox(rat, jb);
    }

    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
                    String fecha = rat.getString("id");
                    fecha = fecha.split(" ")[0];
                    jcb.addItem(fecha);
                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        consultarPorCategoria1 = new pym.ConsultarPorCategoria();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ticket = new javax.swing.JTextField();
        tickErr = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        codigo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 660, 370);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 660, 370));

        ticket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ticket.setToolTipText("");
        ticket.setBorder(null);
        ticket.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                ticketFocusGained(evt);
            }
        });
        ticket.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ticketActionPerformed(evt);
            }
        });
        ticket.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                ticketKeyTyped(evt);
            }
        });
        add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 230, 30));

        tickErr.setForeground(new java.awt.Color(255, 0, 0));
        tickErr.setText("Rellenar Campo");
        tickErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                tickErrFocusGained(evt);
            }
        });
        add(tickErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoLupa.png"))); // NOI18N
        buscar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                buscarMouseExited(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 50, 50));

        codigo1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        codigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo1.setText("Numero de venta (ticket)");
        add(codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void ticketFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ticketFocusGained
    {//GEN-HEADEREND:event_ticketFocusGained
        tickErr.setVisible(false);
    }//GEN-LAST:event_ticketFocusGained

    private void ticketActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ticketActionPerformed
    {//GEN-HEADEREND:event_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketActionPerformed

    private void ticketKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ticketKeyTyped
    {//GEN-HEADEREND:event_ticketKeyTyped

    }//GEN-LAST:event_ticketKeyTyped

    private void tickErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tickErrFocusGained
    {//GEN-HEADEREND:event_tickErrFocusGained

    }//GEN-LAST:event_tickErrFocusGained

    private void buscarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscarMouseEntered
    {//GEN-HEADEREND:event_buscarMouseEntered
        buscar.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscarMouseExited
    {//GEN-HEADEREND:event_buscarMouseExited
        buscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buscarMouseExited

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        if (!ticket.getText().isEmpty())
        {
            jScrollPane1.setVisible(true);
            jTable1.setRowHeight(32);
            m2 = new DefaultTableModel();
            String c2[] =
            {
                "Clave", "Nombre", "Cantidad", "Precio Unitario", "Total"
            };
            m2.setColumnIdentifiers(c2);
            jTable1.setModel(m2);
            try
            {
                ResultSet rat = CRUD.read("Venta_Producto", "*", "WHERE id_Venta=" + ticket.getText());
                while (rat.next())
                {
                    ResultSet ratP = CRUD.read("Producto", "*", "WHERE id=" + rat.getString("id_Producto"));
                    ratP.next();
                    String f[] =
                    {
                        ratP.getString("id"), ratP.getString("nombre"),
                        rat.getString("cantidad"), ratP.getString("precio"), rat.getString("total")
                    };
                    m2.addRow(f);

                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
            jTable1.setEnabled(false);
            if (jTable1.getRowCount()==0)
            {
                jScrollPane1.setVisible(false);
                JOptionPane.showMessageDialog(null, "No se encontró la venta");
            }
        } else
        {
            tickErr.setVisible(true);
            JOptionPane.showMessageDialog(null, "Ingrese una venta");
        }
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel codigo1;
    private pym.ConsultarPorCategoria consultarPorCategoria1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tickErr;
    private javax.swing.JTextField ticket;
    // End of variables declaration//GEN-END:variables
}
