/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import herramientas.Propiedades;
import herramientas.RoundedBorder;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author jonas
 */
public class ConsultaP extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    int bandera = 0;
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);

    public ConsultaP()
    {
        initComponents();
//        opcProducto.setUI(Propiedades.createUI(this));
        proveedor.setUI(new BasicButtonUI());
        general.setUI(new BasicButtonUI());
        categoria.setUI(new BasicButtonUI());
        pintarOpc(new ConsultaPGeneral());
        bandera = 2;
        colorearB(bandera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        proveedor = new javax.swing.JButton();
        general = new javax.swing.JButton();
        categoria = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Consultas");
        add(bienvenidos);
        bienvenidos.setBounds(240, 10, 320, 62);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedor.setBackground(new java.awt.Color(33, 12, 255));
        proveedor.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        proveedor.setForeground(new java.awt.Color(255, 255, 255));
        proveedor.setText("Consultar por Proveedor");
        proveedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                proveedorMouseExited(evt);
            }
        });
        proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                proveedorActionPerformed(evt);
            }
        });
        jPanel2.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        general.setBackground(new java.awt.Color(33, 12, 255));
        general.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        general.setForeground(new java.awt.Color(255, 255, 255));
        general.setText("Consulta general productos");
        general.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                generalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                generalMouseExited(evt);
            }
        });
        general.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generalActionPerformed(evt);
            }
        });
        jPanel2.add(general, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 300, 50));

        categoria.setBackground(new java.awt.Color(33, 12, 255));
        categoria.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        categoria.setForeground(new java.awt.Color(255, 255, 255));
        categoria.setText("Consultar por categoria");
        categoria.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                categoriaMouseExited(evt);
            }
        });
        categoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                categoriaActionPerformed(evt);
            }
        });
        jPanel2.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 50));

        add(jPanel2);
        jPanel2.setBounds(0, 80, 795, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        add(jPanel3);
        jPanel3.setBounds(0, 150, 795, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void proveedorMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proveedorMouseEntered
    {//GEN-HEADEREND:event_proveedorMouseEntered
        if (proveedor.getBackground().equals(colorD))
        {
            proveedor.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_proveedorMouseEntered

    private void proveedorMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proveedorMouseExited
    {//GEN-HEADEREND:event_proveedorMouseExited
        if (proveedor.getBackground().equals(colorS) && bandera != 1)
        {
            proveedor.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_proveedorMouseExited

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proveedorActionPerformed
    {//GEN-HEADEREND:event_proveedorActionPerformed
        pintarOpc(new ConsultarPorProveedor());
        bandera = 1;
        colorearB(bandera);
    }//GEN-LAST:event_proveedorActionPerformed

    private void generalMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_generalMouseEntered
    {//GEN-HEADEREND:event_generalMouseEntered
        if (general.getBackground().equals(colorD))
        {
            general.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_generalMouseEntered

    private void generalMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_generalMouseExited
    {//GEN-HEADEREND:event_generalMouseExited
        if (general.getBackground().equals(colorS) && bandera != 2)
        {
            general.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_generalMouseExited

    private void generalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generalActionPerformed
    {//GEN-HEADEREND:event_generalActionPerformed
        pintarOpc(new ConsultaPGeneral());
        bandera = 2;
        colorearB(bandera);
    }//GEN-LAST:event_generalActionPerformed

    private void categoriaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_categoriaMouseEntered
    {//GEN-HEADEREND:event_categoriaMouseEntered
        if (categoria.getBackground().equals(colorD))
        {
            categoria.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_categoriaMouseEntered

    private void categoriaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_categoriaMouseExited
    {//GEN-HEADEREND:event_categoriaMouseExited
        if (categoria.getBackground().equals(colorS) && bandera != 3)
        {
            categoria.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_categoriaMouseExited

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_categoriaActionPerformed
    {//GEN-HEADEREND:event_categoriaActionPerformed
        pintarOpc(new ConsultarPorCategoria());
        bandera = 3;
        colorearB(bandera);
    }//GEN-LAST:event_categoriaActionPerformed

    public void colorearB(int n)
    {
        switch (n)
        {
            case 1:
                proveedor.setBackground(new Color(30, 161, 255));
                general.setBackground(new Color(33, 12, 255));
                categoria.setBackground(new Color(33, 12, 255));
                break;
            case 2:
                proveedor.setBackground(new Color(33, 12, 255));
                general.setBackground(new Color(30, 161, 255));
                categoria.setBackground(new Color(33, 12, 255));
                break;
            case 3:
                proveedor.setBackground(new Color(33, 12, 255));
                general.setBackground(new Color(33, 12, 255));
                categoria.setBackground(new Color(30, 161, 255));
                break;
            default:
                break;
        }
    }

    public static void pintarOpc(JPanel p)
    {
        p.setSize(795, 610);
        p.setLocation(0, 0);
        jPanel3.removeAll();
        jPanel3.add(p, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JButton categoria;
    private javax.swing.JButton general;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private javax.swing.JButton proveedor;
    // End of variables declaration//GEN-END:variables
}
