/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.RoundedBorder;
import herramientas.TextPrompt;
import herramientas.Validaciones;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class GestionCategorias extends javax.swing.JPanel
{

    /**
     * Creates new form GestionCategorias
     */
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);
    DefaultTableModel m2 = new DefaultTableModel();

    public GestionCategorias()
    {
        initComponents();
        agregarC.setUI(new BasicButtonUI());
        agregarC.setBorder(new RoundedBorder(10));
        agregarC1.setUI(new BasicButtonUI());
        agregarC1.setBorder(new RoundedBorder(10));
        agregarC2.setUI(new BasicButtonUI());
        agregarC2.setBorder(new RoundedBorder(10));
        TextPrompt nombre = new TextPrompt("ABCDE", cat);
        erroresInv(1);
        actualizarTabla();

    }

    public void erroresInv(int id)
    {
        switch (id)
        {
            case 1:
                catErr.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    public void actualizarTabla()
    {
        jPanel1.repaint();
        jPanel1.removeAll();
        System.out.println("a");
        jScrollPane1.setVisible(true);
        jTable1.setRowHeight(32);
        m2 = new DefaultTableModel();
        String c2[] =
        {
            "Nombre Categoria"
        };
        m2.setColumnIdentifiers(c2);
        jTable1.setModel(m2);
        try
        {

            ResultSet rat = CRUD.read("categoria", "*", "ORDER BY id");
            while (rat.next())
            {

                String f[] =
                {
                    rat.getString("nombre")
                };
                m2.addRow(f);

            }

        } catch (Exception e)
        {
            System.out.println("asdasaaaaaaaaaaaaa");
        }
        jTable1.setEnabled(false);
        jTable1.repaint();
        if (!(jTable1.getRowCount() >= 1))
        {
            jPanel1.remove(jScrollPane1);
            jPanel1.setBackground(new Color(204, 204, 204));
            JLabel l = new JLabel();
            l.setText("No hay Categorias");
            l.setBounds(0, 0, 680, 280);
            l.setVerticalAlignment(0);
            l.setHorizontalAlignment(0);
            Font f = new Font(this.getFont().getName(), 3, 48);
            l.setFont(f);
            jPanel1.add(l);
            jPanel1.revalidate();
            jPanel1.repaint();
        } else
        {
            jPanel1.setBackground(Color.white);
            jPanel1.add(jScrollPane1);
            jPanel1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel13 = new javax.swing.JLabel();
        agregarC = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cat = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        catErr = new javax.swing.JLabel();
        agregarC1 = new javax.swing.JButton();
        agregarC2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Categoria");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        agregarC.setBackground(new java.awt.Color(33, 12, 255));
        agregarC.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarC.setForeground(new java.awt.Color(255, 255, 255));
        agregarC.setText("Agregar");
        agregarC.setBorder(null);
        agregarC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarC.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarCMouseExited(evt);
            }
        });
        agregarC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarCActionPerformed(evt);
            }
        });
        add(agregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 300, 10));

        cat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cat.setToolTipText("");
        cat.setBorder(null);
        cat.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                catFocusGained(evt);
            }
        });
        cat.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                catMouseClicked(evt);
            }
        });
        cat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                catActionPerformed(evt);
            }
        });
        cat.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                catKeyTyped(evt);
            }
        });
        add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 300, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 660, 370);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 660, 370));

        catErr.setForeground(new java.awt.Color(255, 0, 0));
        catErr.setText("Rellenar Campo");
        add(catErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 300, -1));

        agregarC1.setBackground(new java.awt.Color(33, 12, 255));
        agregarC1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarC1.setForeground(new java.awt.Color(255, 255, 255));
        agregarC1.setText("Eliminar");
        agregarC1.setBorder(null);
        agregarC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarC1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarC1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarC1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarC1MouseExited(evt);
            }
        });
        agregarC1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarC1ActionPerformed(evt);
            }
        });
        add(agregarC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 170, 40));

        agregarC2.setBackground(new java.awt.Color(33, 12, 255));
        agregarC2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarC2.setForeground(new java.awt.Color(255, 255, 255));
        agregarC2.setText("Modificar");
        agregarC2.setBorder(null);
        agregarC2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarC2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarC2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarC2MouseExited(evt);
            }
        });
        agregarC2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarC2ActionPerformed(evt);
            }
        });
        add(agregarC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarCMouseEntered
    {//GEN-HEADEREND:event_agregarCMouseEntered
        agregarC.setBackground(colorS);
    }//GEN-LAST:event_agregarCMouseEntered

    private void agregarCMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarCMouseExited
    {//GEN-HEADEREND:event_agregarCMouseExited
        agregarC.setBackground(colorD);
    }//GEN-LAST:event_agregarCMouseExited

    private void agregarCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarCActionPerformed
    {//GEN-HEADEREND:event_agregarCActionPerformed
        boolean b = false;
        if (cat.getText().isEmpty())
        {
            b = true;
            catErr.setText("Rellenar Campo");
            catErr.setVisible(true);
        }
        if (!b)
        {
            String valores = "DEFAULT, '" + cat.getText() + "'";
            switch (CRUD.create("Categoria", "", valores, "Categoria"))
            {
                case 0:
                    JOptionPane.showMessageDialog(null, "Categoria REGISTRADA");
                    actualizarTabla();
                    this.repaint();
                    cat.setText("");
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Categoria NO REGISTRADA \n"
                            + "Ya se encuentra en el sistema");
                    break;
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Categoría NO REGISTRADA");
        }

    }//GEN-LAST:event_agregarCActionPerformed

    private void catFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_catFocusGained
    {//GEN-HEADEREND:event_catFocusGained
        catErr.setVisible(false);
    }//GEN-LAST:event_catFocusGained

    private void catMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_catMouseClicked
    {//GEN-HEADEREND:event_catMouseClicked

    }//GEN-LAST:event_catMouseClicked

    private void catActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catActionPerformed
    {//GEN-HEADEREND:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void catKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_catKeyTyped
    {//GEN-HEADEREND:event_catKeyTyped

        Validaciones.validaLetra(evt, 20, cat.getText());

    }//GEN-LAST:event_catKeyTyped

    private void agregarC1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarC1MouseEntered
    {//GEN-HEADEREND:event_agregarC1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarC1MouseEntered

    private void agregarC1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarC1MouseExited
    {//GEN-HEADEREND:event_agregarC1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarC1MouseExited

    private void agregarC1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarC1ActionPerformed
    {//GEN-HEADEREND:event_agregarC1ActionPerformed
        if (cat.getText().isEmpty())
        {
            catErr.setText("Rellenar Campo");
            catErr.setVisible(true);
        } else
        {
            ResultSet rat = CRUD.read("Categoria", "*", "");
            try
            {
                if (rat.next())
                {
                    Object[] options =
                    {
                        "Sí", "Cancelar"
                    };
                    if (JOptionPane.showOptionDialog(null,
                            "¿Deseas continuar? Se eliminara toda la información \n dependiente de esta Categoria",
                            "Confirmación",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[0]) == 0)
                    {
                        try
                        {
                            ResultSet ratCat = CRUD.read("categoria", "*", "WHERE nombre= '" + cat.getText() + "'");
                            if (ratCat.next())
                            {
                                System.out.println("aaa");
                                System.out.println(rat.getString("Nombre"));
                                String sentencia = "nombre = '" + cat.getText() + "'";
                                if (CRUD.delete("categoria", sentencia))
                                {
                                    JOptionPane.showMessageDialog(null, "Categoria ELIMINADA");
                                    actualizarTabla();
                                    cat.setText("");
                                }
                            } else
                            {
                                JOptionPane.showMessageDialog(null, "No se ha encontrado la Categoria");
                            }
                        } catch (Exception e)
                        {
                        }

                    }
                } else
                {
                    JOptionPane.showMessageDialog(null, "No hay Categorias para Eliminar");
                }
            } catch (Exception e)
            {
            }
        }
    }//GEN-LAST:event_agregarC1ActionPerformed

    private void agregarC2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarC2MouseEntered
    {//GEN-HEADEREND:event_agregarC2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarC2MouseEntered

    private void agregarC2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarC2MouseExited
    {//GEN-HEADEREND:event_agregarC2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarC2MouseExited

    private void agregarC2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarC2ActionPerformed
    {//GEN-HEADEREND:event_agregarC2ActionPerformed
        Inventario.pintarOpc(new ModificarCategoria());
    }//GEN-LAST:event_agregarC2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarC;
    private javax.swing.JButton agregarC1;
    private javax.swing.JButton agregarC2;
    private javax.swing.JTextField cat;
    private javax.swing.JLabel catErr;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
