/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import static pym.MenuOpciones.pintarOpc;

/**
 *
 * @author jonas
 */
public class GestionProveedores extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    DefaultTableModel m2 = new DefaultTableModel();
    
    public GestionProveedores()
    {
        initComponents();
        agregar.setUI(new BasicButtonUI());
        eliminar.setUI(new BasicButtonUI());
        eliminar1.setUI(new BasicButtonUI());
        actualizarTabla();
    }
    
    public void actualizarTabla()
    {
        jScrollPane1.setVisible(true);
        jTable1.setRowHeight(32);
        m2 = new DefaultTableModel();
        String c2[] =
        {
            "Proveedor", "Telefono", "Domicilio"
        };
        m2.setColumnIdentifiers(c2);
        jTable1.setModel(m2);
        try
        {
            ResultSet rat = CRUD.read("proveedor", "*", "");
            while (rat.next())
            {
                String f[] =
                {
                    rat.getString("nombre"), rat.getString("telefono"),
                    rat.getString("direccion")
                };
                m2.addRow(f);
                
            }
            
        } catch (Exception e)
        {
            System.out.println("asdasaaaaaaaaaaaaa");
        }
        jTable1.setEnabled(false);
        if (!(jTable1.getRowCount() >= 1))
        {
            jPanel1.remove(jScrollPane1);
            jPanel1.setBackground(new Color(204, 204, 204));
            JLabel l = new JLabel();
            l.setText("No hay Proveedores");
            l.setBounds(0, 0, 680, 280);
            l.setVerticalAlignment(0);
            l.setHorizontalAlignment(0);
            Font f = new Font(this.getFont().getName(), 3, 48);
            l.setFont(f);
            jPanel1.add(l);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setText("Gestion Proveedores");
        add(bienvenidos);
        bienvenidos.setBounds(270, 20, 250, 47);

        agregar.setBackground(new java.awt.Color(33, 12, 255));
        agregar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setBorder(null);
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarMouseExited(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarActionPerformed(evt);
            }
        });
        add(agregar);
        agregar.setBounds(150, 100, 140, 50);

        eliminar.setBackground(new java.awt.Color(33, 12, 255));
        eliminar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.setBorder(null);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                eliminarMouseExited(evt);
            }
        });
        eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarActionPerformed(evt);
            }
        });
        add(eliminar);
        eliminar.setBounds(340, 100, 140, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 680, 370);

        add(jPanel1);
        jPanel1.setBounds(60, 200, 680, 370);

        eliminar1.setBackground(new java.awt.Color(33, 12, 255));
        eliminar1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar1.setText("Modificar");
        eliminar1.setBorder(null);
        eliminar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                eliminar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                eliminar1MouseExited(evt);
            }
        });
        eliminar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminar1ActionPerformed(evt);
            }
        });
        add(eliminar1);
        eliminar1.setBounds(520, 100, 140, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarMouseEntered
    {//GEN-HEADEREND:event_agregarMouseEntered
        agregar.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarMouseExited
    {//GEN-HEADEREND:event_agregarMouseExited
        agregar.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_agregarMouseExited

    private void agregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarActionPerformed
    {//GEN-HEADEREND:event_agregarActionPerformed
        MenuOpciones.pintarOpc(new AltaProveedor());
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminarMouseEntered
    {//GEN-HEADEREND:event_eliminarMouseEntered
        eliminar.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_eliminarMouseEntered

    private void eliminarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminarMouseExited
    {//GEN-HEADEREND:event_eliminarMouseExited
        eliminar.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_eliminarMouseExited

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarActionPerformed
    {//GEN-HEADEREND:event_eliminarActionPerformed
        ResultSet rat = CRUD.read("Proveedor", "*", "");
        try
        {
            if (rat.next())
            {
                MenuOpciones.pintarOpc(new BajaProveedor());
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Proveedores");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void eliminar1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminar1MouseEntered
    {//GEN-HEADEREND:event_eliminar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseEntered

    private void eliminar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminar1MouseExited
    {//GEN-HEADEREND:event_eliminar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseExited

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminar1ActionPerformed
    {//GEN-HEADEREND:event_eliminar1ActionPerformed
        ResultSet rat = CRUD.read("Proveedor", "*", "");
        try
        {
            if (rat.next())
            {
                MenuOpciones.pintarOpc(new ScrollVentanas(new ModificarProveedor()));
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Proveedores");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_eliminar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
