/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author jonas
 */
public class Inventario extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    int bandera = 0;
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);

    public Inventario()
    {
        initComponents();
        agregarE.setUI(new BasicButtonUI());
        agregarG.setUI(new BasicButtonUI());
//        descripcion.setVisible(false);
//        descP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregarE = new javax.swing.JButton();
        agregarG = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Inventario");
        add(bienvenidos);
        bienvenidos.setBounds(300, 10, 200, 47);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarE.setBackground(new java.awt.Color(33, 12, 255));
        agregarE.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        agregarE.setForeground(new java.awt.Color(255, 255, 255));
        agregarE.setText("Agregar existencias");
        agregarE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarEMouseExited(evt);
            }
        });
        agregarE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarEActionPerformed(evt);
            }
        });
        jPanel1.add(agregarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 397, 50));

        agregarG.setBackground(new java.awt.Color(33, 12, 255));
        agregarG.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        agregarG.setForeground(new java.awt.Color(255, 255, 255));
        agregarG.setText("Categorias");
        agregarG.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarGMouseExited(evt);
            }
        });
        agregarG.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarGActionPerformed(evt);
            }
        });
        jPanel1.add(agregarG, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 0, 398, 50));

        add(jPanel1);
        jPanel1.setBounds(0, 60, 795, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        add(jPanel2);
        jPanel2.setBounds(0, 110, 795, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarEActionPerformed
    {//GEN-HEADEREND:event_agregarEActionPerformed
        ResultSet rat = CRUD.read("Producto", "*", "");
        try
        {
            if (rat.next())
            {
                pintarOpc(new AgregarExistencias());
                bandera = 1;
                colorearB(bandera);
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Productos");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_agregarEActionPerformed

    private void agregarEMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarEMouseEntered
    {//GEN-HEADEREND:event_agregarEMouseEntered
        if (agregarE.getBackground().equals(colorD))
        {
            agregarE.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_agregarEMouseEntered

    private void agregarEMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarEMouseExited
    {//GEN-HEADEREND:event_agregarEMouseExited
        if (agregarE.getBackground().equals(colorS) && bandera != 1)
        {
            agregarE.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_agregarEMouseExited

    private void agregarGActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarGActionPerformed
    {//GEN-HEADEREND:event_agregarGActionPerformed
        pintarOpc(new GestionCategorias());
        bandera = 2;
        colorearB(bandera);
    }//GEN-LAST:event_agregarGActionPerformed

    private void agregarGMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarGMouseEntered
    {//GEN-HEADEREND:event_agregarGMouseEntered
        if (agregarG.getBackground().equals(colorD))
        {
            agregarG.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_agregarGMouseEntered

    private void agregarGMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarGMouseExited
    {//GEN-HEADEREND:event_agregarGMouseExited
        if (agregarG.getBackground().equals(colorS) && bandera != 2)
        {
            agregarG.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_agregarGMouseExited

    public void colorearB(int n)
    {
        switch (n)
        {
            case 1:
                agregarE.setBackground(new Color(30, 161, 255));
                agregarG.setBackground(new Color(33, 12, 255));
                break;
            case 2:
                agregarE.setBackground(new Color(33, 12, 255));
                agregarG.setBackground(new Color(30, 161, 255));
                break;
            default:
                break;
        }
    }

    public static void pintarOpc(JPanel p)
    {
        p.setSize(795, 610);
        p.setLocation(0, 0);
        jPanel2.removeAll();
        jPanel2.add(p, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarE;
    private javax.swing.JButton agregarG;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
