/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import clases.conex.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import static pym.VtnPrincipal.pintar;

/**
 *
 * @author PC
 */
public class MenuOpciones extends javax.swing.JPanel
{

    /**
     * Creates new form MenuOpciones
     */
    int bandera = 0;
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);

    public MenuOpciones()
    {
        initComponents();
        altaP.setUI(new BasicButtonUI());
        bajaP.setUI(new BasicButtonUI());
        consultaP.setUI(new BasicButtonUI());
        modificarP.setUI(new BasicButtonUI());
        devoluciones.setUI(new BasicButtonUI());
        regresar.setUI(new BasicButtonUI());
        devoluciones.setUI(new BasicButtonUI());
        registroV.setUI(new BasicButtonUI());
        proveedores.setUI(new BasicButtonUI());
        inventario.setUI(new BasicButtonUI());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        altaP = new javax.swing.JButton();
        bajaP = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        registroV = new javax.swing.JButton();
        modificarP = new javax.swing.JButton();
        consultaP = new javax.swing.JButton();
        devoluciones = new javax.swing.JButton();
        proveedores = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        opciones = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(33, 12, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAbastoF_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 160));

        altaP.setBackground(new java.awt.Color(33, 12, 255));
        altaP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        altaP.setForeground(new java.awt.Color(255, 255, 255));
        altaP.setText("Alta Producto");
        altaP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                altaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                altaPMouseExited(evt);
            }
        });
        altaP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                altaPActionPerformed(evt);
            }
        });
        jPanel1.add(altaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 40));

        bajaP.setBackground(new java.awt.Color(33, 12, 255));
        bajaP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        bajaP.setForeground(new java.awt.Color(255, 255, 255));
        bajaP.setText("Baja Producto");
        bajaP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaPMouseExited(evt);
            }
        });
        bajaP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bajaPActionPerformed(evt);
            }
        });
        jPanel1.add(bajaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 40));

        regresar.setBackground(new java.awt.Color(33, 12, 255));
        regresar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                regresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                regresarMouseExited(evt);
            }
        });
        regresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 230, 40));

        registroV.setBackground(new java.awt.Color(33, 12, 255));
        registroV.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        registroV.setForeground(new java.awt.Color(255, 255, 255));
        registroV.setText("Registro Ventas");
        registroV.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                registroVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                registroVMouseExited(evt);
            }
        });
        registroV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registroVActionPerformed(evt);
            }
        });
        jPanel1.add(registroV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 230, 40));

        modificarP.setBackground(new java.awt.Color(33, 12, 255));
        modificarP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        modificarP.setForeground(new java.awt.Color(255, 255, 255));
        modificarP.setText("Modificar Producto");
        modificarP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                modificarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                modificarPMouseExited(evt);
            }
        });
        modificarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarPActionPerformed(evt);
            }
        });
        jPanel1.add(modificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 40));

        consultaP.setBackground(new java.awt.Color(33, 12, 255));
        consultaP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        consultaP.setForeground(new java.awt.Color(255, 255, 255));
        consultaP.setText("Consultar Producto");
        consultaP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                consultaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                consultaPMouseExited(evt);
            }
        });
        consultaP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consultaPActionPerformed(evt);
            }
        });
        jPanel1.add(consultaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 40));

        devoluciones.setBackground(new java.awt.Color(33, 12, 255));
        devoluciones.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        devoluciones.setForeground(new java.awt.Color(255, 255, 255));
        devoluciones.setText("Devoluciones");
        devoluciones.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                devolucionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                devolucionesMouseExited(evt);
            }
        });
        devoluciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                devolucionesActionPerformed(evt);
            }
        });
        jPanel1.add(devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 40));

        proveedores.setBackground(new java.awt.Color(33, 12, 255));
        proveedores.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        proveedores.setForeground(new java.awt.Color(255, 255, 255));
        proveedores.setText("Proveedores");
        proveedores.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                proveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                proveedoresMouseExited(evt);
            }
        });
        proveedores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                proveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 40));

        inventario.setBackground(new java.awt.Color(33, 12, 255));
        inventario.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setText("Inventario");
        inventario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                inventarioMouseExited(evt);
            }
        });
        inventario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                inventarioActionPerformed(evt);
            }
        });
        jPanel1.add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 230, 40));

        add(jPanel1);
        jPanel1.setBounds(0, 0, 230, 720);

        opciones.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout opcionesLayout = new javax.swing.GroupLayout(opciones);
        opciones.setLayout(opcionesLayout);
        opcionesLayout.setHorizontalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        opcionesLayout.setVerticalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(opciones);
        opciones.setBounds(230, 0, 795, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_regresarActionPerformed
    {//GEN-HEADEREND:event_regresarActionPerformed
        pintar(new VentaProducto());
    }//GEN-LAST:event_regresarActionPerformed

    private void altaPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_altaPActionPerformed
    {//GEN-HEADEREND:event_altaPActionPerformed

        boolean p = false, c = false;
        String mensaje = "";
        if (CRUD.verificarProveedor() < 1 && CRUD.verificarCategoria() < 1)
        {
            mensaje = "No existen proveedores y categorias";
        }

        if (CRUD.verificarCategoria() < 1 && CRUD.verificarProveedor() > 0)
        {
            mensaje = "No existen categorias";
        }
        if (CRUD.verificarProveedor() < 1 && CRUD.verificarCategoria() > 0)
        {
            mensaje = "No existen proveedores";
        }
        if (CRUD.verificarProveedor() > 0 && CRUD.verificarCategoria() > 0)
        {
            pintarOpc(new AltasProductos());
            bandera = 1;
            colorearB(bandera);
        } else
        {
            JOptionPane.showMessageDialog(null, mensaje);
        }


    }//GEN-LAST:event_altaPActionPerformed

    private void altaPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_altaPMouseEntered
    {//GEN-HEADEREND:event_altaPMouseEntered
        if (altaP.getBackground().equals(colorD))
        {
            altaP.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_altaPMouseEntered

    private void altaPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_altaPMouseExited
    {//GEN-HEADEREND:event_altaPMouseExited
        if (altaP.getBackground().equals(colorS) && bandera != 1)
        {
            altaP.setBackground(new Color(33, 12, 255));
        }

    }//GEN-LAST:event_altaPMouseExited

    private void bajaPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bajaPActionPerformed
    {//GEN-HEADEREND:event_bajaPActionPerformed
        ResultSet rat = CRUD.read("Producto", "*", "");

        try
        {
            if (rat.next())
            {
                pintarOpc(new BajaProductos());
                bandera = 2;
                colorearB(bandera);
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Productos");
                VtnPrincipal.pintar(new MenuOpciones());
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_bajaPActionPerformed

    private void bajaPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaPMouseEntered
    {//GEN-HEADEREND:event_bajaPMouseEntered
        if (bajaP.getBackground().equals(colorD))
        {
            bajaP.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_bajaPMouseEntered

    private void bajaPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaPMouseExited
    {//GEN-HEADEREND:event_bajaPMouseExited
        if (bajaP.getBackground().equals(colorS) && bandera != 2)
        {
            bajaP.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_bajaPMouseExited

    private void registroVMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_registroVMouseEntered
    {//GEN-HEADEREND:event_registroVMouseEntered
        if (registroV.getBackground().equals(colorD))
        {
            registroV.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_registroVMouseEntered

    private void registroVMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_registroVMouseExited
    {//GEN-HEADEREND:event_registroVMouseExited
        if (registroV.getBackground().equals(colorS) && bandera != 7)
        {
            registroV.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_registroVMouseExited

    private void registroVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registroVActionPerformed
    {//GEN-HEADEREND:event_registroVActionPerformed
        pintarOpc(new RegistroV());
        bandera = 7;
        colorearB(bandera);
    }//GEN-LAST:event_registroVActionPerformed

    private void modificarPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modificarPMouseEntered
    {//GEN-HEADEREND:event_modificarPMouseEntered
        if (modificarP.getBackground().equals(colorD))
        {
            modificarP.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_modificarPMouseEntered

    private void modificarPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modificarPMouseExited
    {//GEN-HEADEREND:event_modificarPMouseExited
        if (modificarP.getBackground().equals(colorS) && bandera != 4)
        {
            modificarP.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_modificarPMouseExited

    private void modificarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarPActionPerformed
    {//GEN-HEADEREND:event_modificarPActionPerformed
        ResultSet rat = CRUD.read("Producto", "*", "");
        try
        {
            if (rat.next())
            {
                pintarOpc(new ScrollVentanas(new ModificarProducto()));
                bandera = 4;
                colorearB(bandera);
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Productos");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_modificarPActionPerformed

    private void consultaPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_consultaPMouseEntered
    {//GEN-HEADEREND:event_consultaPMouseEntered
        if (consultaP.getBackground().equals(colorD))
        {
            consultaP.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_consultaPMouseEntered

    private void consultaPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_consultaPMouseExited
    {//GEN-HEADEREND:event_consultaPMouseExited
        if (consultaP.getBackground().equals(colorS) && bandera != 3)
        {
            consultaP.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_consultaPMouseExited

    private void consultaPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consultaPActionPerformed
    {//GEN-HEADEREND:event_consultaPActionPerformed
        ResultSet rat = CRUD.read("Producto", "*", "");
        try
        {
            if (rat.next())
            {
                pintarOpc(new ConsultaP());
                bandera = 3;
                colorearB(bandera);
            } else
            {
                JOptionPane.showMessageDialog(null, "No hay Productos");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_consultaPActionPerformed

    private void devolucionesMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_devolucionesMouseEntered
    {//GEN-HEADEREND:event_devolucionesMouseEntered
        if (devoluciones.getBackground().equals(colorD))
        {
            devoluciones.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_devolucionesMouseEntered

    private void devolucionesMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_devolucionesMouseExited
    {//GEN-HEADEREND:event_devolucionesMouseExited
        if (devoluciones.getBackground().equals(colorS) && bandera != 5)
        {
            devoluciones.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_devolucionesMouseExited

    private void devolucionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_devolucionesActionPerformed
    {//GEN-HEADEREND:event_devolucionesActionPerformed
        pintarOpc(new ScrollVentanas(new Devoluciones()));
        bandera = 5;
        colorearB(bandera);
    }//GEN-LAST:event_devolucionesActionPerformed

    private void proveedoresMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proveedoresMouseEntered
    {//GEN-HEADEREND:event_proveedoresMouseEntered
        if (proveedores.getBackground().equals(colorD))
        {
            proveedores.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_proveedoresMouseEntered

    private void proveedoresMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proveedoresMouseExited
    {//GEN-HEADEREND:event_proveedoresMouseExited
        if (proveedores.getBackground().equals(colorS) && bandera != 6)
        {
            proveedores.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_proveedoresMouseExited

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proveedoresActionPerformed
    {//GEN-HEADEREND:event_proveedoresActionPerformed
        pintarOpc(new GestionProveedores());
        bandera = 6;
        colorearB(bandera);
    }//GEN-LAST:event_proveedoresActionPerformed

    private void regresarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_regresarMouseEntered
    {//GEN-HEADEREND:event_regresarMouseEntered
        regresar.setBackground(colorS);
    }//GEN-LAST:event_regresarMouseEntered

    private void regresarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_regresarMouseExited
    {//GEN-HEADEREND:event_regresarMouseExited
        regresar.setBackground(colorD);
    }//GEN-LAST:event_regresarMouseExited

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inventarioActionPerformed
    {//GEN-HEADEREND:event_inventarioActionPerformed
        pintarOpc(new Inventario());
        bandera = 8;
        colorearB(bandera);
    }//GEN-LAST:event_inventarioActionPerformed

    private void inventarioMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_inventarioMouseExited
    {//GEN-HEADEREND:event_inventarioMouseExited
        if (inventario.getBackground().equals(colorS) && bandera != 8)
        {
            inventario.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_inventarioMouseExited

    private void inventarioMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_inventarioMouseEntered
    {//GEN-HEADEREND:event_inventarioMouseEntered
        if (inventario.getBackground().equals(colorD))
        {
            inventario.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_inventarioMouseEntered

    public static void pintarOpc(JPanel p)
    {
        p.setSize(795, 720);
        p.setLocation(0, 0);
        opciones.removeAll();
        opciones.add(p, BorderLayout.CENTER);
        opciones.revalidate();
        opciones.repaint();
    }

    public void colorearB(int n)
    {
        switch (n)
        {
            case 1:
                altaP.setBackground(new Color(30, 161, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 2:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(30, 161, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 3:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(30, 161, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 4:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(30, 161, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 5:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(30, 161, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 6:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(30, 161, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 7:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(30, 161, 255));
                inventario.setBackground(new Color(33, 12, 255));
                break;
            case 8:
                altaP.setBackground(new Color(33, 12, 255));
                bajaP.setBackground(new Color(33, 12, 255));
                consultaP.setBackground(new Color(33, 12, 255));
                modificarP.setBackground(new Color(33, 12, 255));
                devoluciones.setBackground(new Color(33, 12, 255));
                proveedores.setBackground(new Color(33, 12, 255));
                registroV.setBackground(new Color(33, 12, 255));
                inventario.setBackground(new Color(30, 161, 255));
                break;
            default:
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaP;
    private javax.swing.JButton bajaP;
    private javax.swing.JButton consultaP;
    private javax.swing.JButton devoluciones;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarP;
    private static javax.swing.JPanel opciones;
    private javax.swing.JButton proveedores;
    private javax.swing.JButton registroV;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
