/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.TextPrompt;
import herramientas.Validaciones;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jonas
 */
public class ModificarProveedor extends javax.swing.JPanel
{

    boolean estado;
    DefaultTableModel m2 = new DefaultTableModel();

    /**
     * Creates new form AltasProductos
     */
    public ModificarProveedor()
    {
        initComponents();
        opcProveedor.setUI(Propiedades.createUI(this));
        bajaP.setUI(new BasicButtonUI());
        bajaP.setBorder(new RoundedBorder(10));
        atras.setUI(new BasicButtonUI());
        atras.setBorder(new RoundedBorder(10));
        consultaCombo(opcProveedor, "Proveedor", "");
        TextPrompt buscaProv = new TextPrompt("Ingrese id o nombre del Proveedor", buscaProveedor);
        listenersBuscadores();
        buscaProveedor.setEnabled(false);
        sc.setVisible(false);
        nomProErr.setVisible(false);
        telefonoErr.setVisible(false);
        direErr.setVisible(false);
        TextPrompt nombre = new TextPrompt("ABCDE", nombrePrv);
        TextPrompt tel = new TextPrompt("0123456789", telefono);
        TextPrompt dire = new TextPrompt("ABCDE", direccion);
    }

    // Carga de nuevo los productos a el comboBox
    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione un Proovedor");
        ResultSet rat = CRUD.read(tabla, "*", sentencia);
        cargarComboBox(rat, jb);
    }

    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
                    jcb.addItem(rat.getString("id") + ":  " + rat.getString("nombre"));
                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        } else
        {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        opcProveedor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        bajaP = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        buscaProveedor = new javax.swing.JTextField();
        nombreB = new javax.swing.JRadioButton();
        idB = new javax.swing.JRadioButton();
        sc = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombrePrv = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        nomProErr = new javax.swing.JLabel();
        telefonoErr = new javax.swing.JLabel();
        direErr = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Modifica Proveedor");
        add(bienvenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 390, -1));

        opcProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un proveedor" }));
        opcProveedor.setToolTipText("");
        opcProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcProveedor.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                opcProveedorItemStateChanged(evt);
            }
        });
        opcProveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcProveedorActionPerformed(evt);
            }
        });
        add(opcProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 350, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Proveedor");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 24));

        bajaP.setBackground(new java.awt.Color(33, 12, 255));
        bajaP.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        bajaP.setForeground(new java.awt.Color(255, 255, 255));
        bajaP.setText("Modificar");
        bajaP.setBorder(null);
        bajaP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bajaP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bajaP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaPMouseExited(evt);
            }
        });
        bajaP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bajaPActionPerformed(evt);
            }
        });
        add(bajaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 700, 140, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 350, 10));

        buscaProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscaProveedor.setToolTipText("");
        buscaProveedor.setBorder(null);
        buscaProveedor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                buscaProveedorFocusGained(evt);
            }
        });
        buscaProveedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buscaProveedorMouseClicked(evt);
            }
        });
        buscaProveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaProveedorActionPerformed(evt);
            }
        });
        buscaProveedor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                buscaProveedorKeyTyped(evt);
            }
        });
        add(buscaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 350, 30));

        nombreB.setText("Buscar con Nombre");
        nombreB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreBActionPerformed(evt);
            }
        });
        add(nombreB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, -1));

        idB.setText("Buscar con ID");
        idB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                idBActionPerformed(evt);
            }
        });
        add(idB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sc.setViewportView(table);

        add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 540, 60));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoAtras.png"))); // NOI18N
        atras.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                atrasMouseExited(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atrasActionPerformed(evt);
            }
        });
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Proveedor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 210, 20));

        nombrePrv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePrv.setToolTipText("");
        nombrePrv.setBorder(null);
        nombrePrv.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nombrePrvFocusGained(evt);
            }
        });
        nombrePrv.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                nombrePrvMouseClicked(evt);
            }
        });
        nombrePrv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombrePrvActionPerformed(evt);
            }
        });
        nombrePrv.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombrePrvKeyTyped(evt);
            }
        });
        add(nombrePrv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 350, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 350, 10));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Telefono");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 230, 20));

        telefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono.setToolTipText("");
        telefono.setBorder(null);
        telefono.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                telefonoFocusGained(evt);
            }
        });
        telefono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telefonoKeyTyped(evt);
            }
        });
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 350, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 350, 10));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Dirección");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 200, 20));

        direccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        direccion.setToolTipText("");
        direccion.setBorder(null);
        direccion.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                direccionFocusGained(evt);
            }
        });
        direccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                direccionActionPerformed(evt);
            }
        });
        direccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                direccionKeyTyped(evt);
            }
        });
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 350, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 350, 10));

        nomProErr.setForeground(new java.awt.Color(255, 0, 0));
        nomProErr.setText("Rellenar Campo");
        add(nomProErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 350, -1));

        telefonoErr.setForeground(new java.awt.Color(255, 0, 0));
        telefonoErr.setText("Rellenar Campo");
        telefonoErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                telefonoErrFocusGained(evt);
            }
        });
        add(telefonoErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 350, -1));

        direErr.setForeground(new java.awt.Color(255, 0, 0));
        direErr.setText("Rellenar Campo");
        direErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                direErrFocusGained(evt);
            }
        });
        add(direErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 350, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 720, 60, 80));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Campos");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void opcProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcProveedorActionPerformed
    {//GEN-HEADEREND:event_opcProveedorActionPerformed
        sc.setVisible(false);
        if (opcProveedor.getSelectedIndex() != 0 && opcProveedor.getItemCount() > 1)
        {
            sc.setVisible(true);
            table.setRowHeight(32);
            m2 = new DefaultTableModel();
            String c2[] =
            {
                "Nombre", "Telefono", "Dirección"
            };
            m2.setColumnIdentifiers(c2);
            table.setModel(m2);
            try
            {
                String sentencia = "id=" + (opcProveedor.getSelectedItem().toString().split(":")[0]);
                ResultSet rat = CRUD.read("proveedor", "*", "WHERE " + sentencia);
                rat.next();
                String f[] =
                {
                    rat.getString("nombre"), rat.getString("telefono"),
                    rat.getString("direccion")
                };
                m2.addRow(f);
                nombrePrv.setText(rat.getString("nombre"));
                telefono.setText(rat.getString("telefono"));
                direccion.setText(rat.getString("direccion"));
            } catch (Exception e)
            {
                System.out.println("asdasaaaaaaaaaaaaa");
            }
            table.setEnabled(false);
        } else
        {
            nombrePrv.setText("");
            telefono.setText("");
            direccion.setText("");
        }
    }//GEN-LAST:event_opcProveedorActionPerformed

    private void bajaPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaPMouseEntered
    {//GEN-HEADEREND:event_bajaPMouseEntered
        bajaP.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_bajaPMouseEntered

    private void bajaPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaPMouseExited
    {//GEN-HEADEREND:event_bajaPMouseExited
        bajaP.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_bajaPMouseExited

    private void bajaPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bajaPActionPerformed
    {//GEN-HEADEREND:event_bajaPActionPerformed

        if (opcProveedor.getSelectedIndex() > 0)
        {

            boolean b = false;
            if (nombrePrv.getText().isEmpty())
            {
                b = true;
                nomProErr.setText("Rellenar Campo");
                nomProErr.setVisible(true);
            }
            if (telefono.getText().isEmpty())
            {
                b = true;
                telefonoErr.setText("Rellenar Campo");
                telefonoErr.setVisible(true);
            }
            if (direccion.getText().isEmpty())
            {
                b = true;
                direErr.setText("Rellenar Campo");
                direErr.setVisible(true);
            }
            if (!b)
            {
                Object[] options =
                {
                    "Sí", "Cancelar"
                };
                if (JOptionPane.showOptionDialog(null,
                        "¿Seguro que desea actualizar?",
                        "Confirmación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]) == 0)
                {
                    String valores = "nombre = '" + nombrePrv.getText() + "',"
                            + "telefono = '" + telefono.getText() + "',"
                            + "direccion = '" + direccion.getText() + "'";
                    String sentencia = "id = " + opcProveedor.getSelectedItem().toString().split(":")[0];
                    switch (CRUD.update("Proveedor", sentencia, valores))
                    {
                        case 0:
                            consultaCombo(opcProveedor, "Proveedor", "");
                            nombrePrv.setText("");
                            telefono.setText("");
                            direccion.setText("");
                            idB.setSelected(false);
                            nombreB.setSelected(false);
                            buscaProveedor.setText("");
                            buscaProveedor.setEnabled(false);
                            opcProveedor.setSelectedIndex(0);
                            JOptionPane.showMessageDialog(null, "Se ha actualizado la información");
                            break;
                        case 1:
                            JOptionPane.showMessageDialog(null, "Proovedor NO ACTUALIZADO \n La clave ya se encuentra en el sistema");
                            break;
                        case 2:
                            JOptionPane.showMessageDialog(null, "Proovedor NO ACTUALIZADO \n Los datos del Proveedor ya se encuentran en el sistema"
                                    + "\n (Nombre)");
                            break;
                    }
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "Proveedor no ACTUALIZADO");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado Proveedor");
        }

    }//GEN-LAST:event_bajaPActionPerformed

    private void opcProveedorItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_opcProveedorItemStateChanged
    {//GEN-HEADEREND:event_opcProveedorItemStateChanged


    }//GEN-LAST:event_opcProveedorItemStateChanged

    private void buscaProveedorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buscaProveedorFocusGained
    {//GEN-HEADEREND:event_buscaProveedorFocusGained
        opcProveedor.setSelectedIndex(0);
    }//GEN-LAST:event_buscaProveedorFocusGained

    private void buscaProveedorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaProveedorMouseClicked
    {//GEN-HEADEREND:event_buscaProveedorMouseClicked

    }//GEN-LAST:event_buscaProveedorMouseClicked

    private void buscaProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaProveedorActionPerformed
    {//GEN-HEADEREND:event_buscaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProveedorActionPerformed

    private void buscaProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaProveedorKeyTyped
    {//GEN-HEADEREND:event_buscaProveedorKeyTyped
        if (estado)
        {
            Validaciones.validaEntero(evt, 13, buscaProveedor.getText());
        } else
        {
            Validaciones.validaLetra(evt, 20, buscaProveedor.getText());
        }
    }//GEN-LAST:event_buscaProveedorKeyTyped

    private void idBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_idBActionPerformed
    {//GEN-HEADEREND:event_idBActionPerformed
        buscaProveedor.setText("");
        if (idB.isSelected())
        {
            buscaProveedor.setText("");
            estado = true;
            if (nombreB.isSelected())
            {
                nombreB.setSelected(false);
            }
            buscaProveedor.setEnabled(true);
        } else
        {
            if (nombreB.isSelected())
            {
                buscaProveedor.setEnabled(true);
            } else
            {
                buscaProveedor.setEnabled(false);
            }
        }
    }//GEN-LAST:event_idBActionPerformed

    private void nombreBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreBActionPerformed
    {//GEN-HEADEREND:event_nombreBActionPerformed
        buscaProveedor.setText("");
        if (nombreB.isSelected())
        {
            estado = false;
            if (idB.isSelected())
            {
                idB.setSelected(false);
            }
            buscaProveedor.setEnabled(true);
        } else
        {
            if (idB.isSelected())
            {
                buscaProveedor.setEnabled(true);
            } else
            {
                buscaProveedor.setEnabled(false);
            }
        }
    }//GEN-LAST:event_nombreBActionPerformed

    private void atrasMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseEntered
    {//GEN-HEADEREND:event_atrasMouseEntered
        atras.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_atrasMouseEntered

    private void atrasMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseExited
    {//GEN-HEADEREND:event_atrasMouseExited
        atras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_atrasMouseExited

    private void atrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atrasActionPerformed
    {//GEN-HEADEREND:event_atrasActionPerformed
        MenuOpciones.pintarOpc(new GestionProveedores());
    }//GEN-LAST:event_atrasActionPerformed

    private void nombrePrvFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombrePrvFocusGained
    {//GEN-HEADEREND:event_nombrePrvFocusGained
        nomProErr.setVisible(false);
    }//GEN-LAST:event_nombrePrvFocusGained

    private void nombrePrvMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombrePrvMouseClicked
    {//GEN-HEADEREND:event_nombrePrvMouseClicked

    }//GEN-LAST:event_nombrePrvMouseClicked

    private void nombrePrvActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombrePrvActionPerformed
    {//GEN-HEADEREND:event_nombrePrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePrvActionPerformed

    private void nombrePrvKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombrePrvKeyTyped
    {//GEN-HEADEREND:event_nombrePrvKeyTyped
        Validaciones.validaLetra(evt, 20, nombrePrv.getText());
    }//GEN-LAST:event_nombrePrvKeyTyped

    private void telefonoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoFocusGained
    {//GEN-HEADEREND:event_telefonoFocusGained
        telefonoErr.setVisible(false);
    }//GEN-LAST:event_telefonoFocusGained

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_telefonoActionPerformed
    {//GEN-HEADEREND:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telefonoKeyTyped
    {//GEN-HEADEREND:event_telefonoKeyTyped
        Validaciones.validaEntero(evt, 10, telefono.getText());
    }//GEN-LAST:event_telefonoKeyTyped

    private void direccionFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direccionFocusGained
    {//GEN-HEADEREND:event_direccionFocusGained
        direErr.setVisible(false);
    }//GEN-LAST:event_direccionFocusGained

    private void direccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_direccionActionPerformed
    {//GEN-HEADEREND:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void direccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_direccionKeyTyped
    {//GEN-HEADEREND:event_direccionKeyTyped
        Validaciones.validaAlfaNum(evt, 60, direccion.getText());
    }//GEN-LAST:event_direccionKeyTyped

    private void telefonoErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoErrFocusGained
    {//GEN-HEADEREND:event_telefonoErrFocusGained

    }//GEN-LAST:event_telefonoErrFocusGained

    private void direErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direErrFocusGained
    {//GEN-HEADEREND:event_direErrFocusGained

    }//GEN-LAST:event_direErrFocusGained

    public void listenersBuscadores()
    {
        buscaProveedor.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                // Acción cuando se inserta texto
                if (buscaProveedor.getText().isEmpty())
                {
                    consultaCombo(opcProveedor, "Proveedor", "");
                } else
                {
                    try
                    {
                        Integer.parseInt(buscaProveedor.getText());
                        String sentencia = "WHERE id = " + buscaProveedor.getText() + "";
                        System.out.println(sentencia);
                        consultaCombo(opcProveedor, "Proveedor", sentencia);
                    } catch (Exception er)
                    {
                        String sentencia = "WHERE nombre LIKE '%" + buscaProveedor.getText() + "%'";
                        System.out.println(sentencia);
                        consultaCombo(opcProveedor, "Proveedor", sentencia);
                    }
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e)
            {
                // Acción cuando se elimina texto
                if (buscaProveedor.getText().isEmpty())
                {
                    consultaCombo(opcProveedor, "Proveedor", "");
                } else
                {
                    try
                    {
                        Integer.parseInt(buscaProveedor.getText());
                        String sentencia = "WHERE id = " + buscaProveedor.getText() + "";
                        System.out.println(sentencia);
                        consultaCombo(opcProveedor, "Proveedor", sentencia);
                    } catch (Exception er)
                    {
                        String sentencia = "WHERE nombre LIKE '%" + buscaProveedor.getText() + "%'";
                        System.out.println(sentencia);
                        consultaCombo(opcProveedor, "Proveedor", sentencia);
                    }
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e)
            {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton bajaP;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JTextField buscaProveedor;
    private javax.swing.JLabel direErr;
    private javax.swing.JTextField direccion;
    private javax.swing.JRadioButton idB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nomProErr;
    private javax.swing.JRadioButton nombreB;
    private javax.swing.JTextField nombrePrv;
    private javax.swing.JComboBox<String> opcProveedor;
    private javax.swing.JScrollPane sc;
    private javax.swing.JTable table;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoErr;
    // End of variables declaration//GEN-END:variables
}
