/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicButtonUI;
import herramientas.TextPrompt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonas
 */
public class ModificarProd extends javax.swing.JPanel
{

    boolean estado;
    DefaultTableModel m2 = new DefaultTableModel();
    int idProv = -1;
    int idCat = -1;

    /**
     * Creates new form AltasProductos
     */
    public ModificarProd()
    {
        initComponents();
        opcProductos.setUI(Propiedades.createUI(this));
        opcProveedor.setUI(Propiedades.createUI(this));
        opcCategoria.setUI(Propiedades.createUI(this));
        agregarP.setUI(new BasicButtonUI());
        consultaCombo(opcProductos, "Producto", "");
        agregarP.setBorder(new RoundedBorder(10));
        ResultSet rat = CRUD.read("proveedor", "*", "");
        cargarComboBox(rat, opcProveedor);
        ResultSet rat2 = CRUD.read("categoria", "*", "");
        cargarComboBox(rat2, opcCategoria);
        campos();
        erroresInv(0);
        jScrollPane1.setVisible(false);
        buscaProducto.setEnabled(false);
    }

    public void campos()
    {
        TextPrompt buscaProd = new TextPrompt("Ingrese clave o nombre del Producto", buscaProducto);
        TextPrompt nombre = new TextPrompt("ABDCD", nombrePro);
        TextPrompt clave = new TextPrompt("0123456789", claveP);
        TextPrompt unidad = new TextPrompt("UN", unidadM);
        TextPrompt mag = new TextPrompt("12345", magnitudM);
        TextPrompt precio = new TextPrompt("00.00", precioUnitario);
        TextPrompt cant = new TextPrompt("12345", cantidad);
    }

    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione un producto");
        ResultSet rat = CRUD.read(tabla, "*", sentencia);
        cargarComboBox(rat, jb);
    }

    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
                    jcb.addItem(rat.getString("id") + ":  " + rat.getString("nombre"));
                }
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        } else
        {

        }
    }

    public void erroresInv(int id)
    {
        switch (id)
        {
            case 1:
                opcCatErr.setVisible(false);
                break;
            case 2:
                claErr.setVisible(false);
                break;
            case 3:
                uniErr.setVisible(false);
                break;
            case 4:
                magErr.setVisible(false);
                break;
            case 5:
                precErr.setVisible(false);
                break;
            case 6:
                cantErr.setVisible(false);
                break;
            case 0:
                proErr.setVisible(false);
                claErr.setVisible(false);
                uniErr.setVisible(false);
                magErr.setVisible(false);
                precErr.setVisible(false);
                cantErr.setVisible(false);
                opcCatErr.setVisible(false);
                opcProvErr.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        opcProveedor = new javax.swing.JComboBox<>();
        agregarP = new javax.swing.JButton();
        magnitudM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombrePro = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        precioUnitario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        claErr = new javax.swing.JLabel();
        cantErr = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        opcCategoria = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        unidadM = new javax.swing.JTextField();
        bienvenidos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        magErr = new javax.swing.JLabel();
        uniErr = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        opcCatErr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        claveP = new javax.swing.JTextField();
        precErr = new javax.swing.JLabel();
        proErr = new javax.swing.JLabel();
        opcProvErr = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buscaProducto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        claveB = new javax.swing.JRadioButton();
        nombreB = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        opcProductos = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Proveedor");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 440, 130, 24);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(410, 730, 350, 10);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(30, 640, 350, 10);

        opcProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un proveedor" }));
        opcProveedor.setToolTipText("");
        opcProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcProveedor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcProveedorFocusGained(evt);
            }
        });
        opcProveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(opcProveedor);
        opcProveedor.setBounds(30, 470, 350, 28);

        agregarP.setBackground(new java.awt.Color(33, 12, 255));
        agregarP.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarP.setForeground(new java.awt.Color(255, 255, 255));
        agregarP.setText("Modificar");
        agregarP.setBorder(null);
        agregarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                agregarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarPMouseExited(evt);
            }
        });
        agregarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarPActionPerformed(evt);
            }
        });
        jPanel2.add(agregarP);
        agregarP.setBounds(310, 890, 140, 50);

        magnitudM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        magnitudM.setToolTipText("");
        magnitudM.setBorder(null);
        magnitudM.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                magnitudMFocusGained(evt);
            }
        });
        magnitudM.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                magnitudMMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                magnitudMMousePressed(evt);
            }
        });
        magnitudM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                magnitudMActionPerformed(evt);
            }
        });
        magnitudM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                magnitudMKeyTyped(evt);
            }
        });
        jPanel2.add(magnitudM);
        magnitudM.setBounds(410, 700, 350, 30);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Cantidad (Stoks)");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(410, 760, 200, 20);

        nombrePro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePro.setToolTipText("");
        nombrePro.setBorder(null);
        nombrePro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombrePro.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nombreProFocusGained(evt);
            }
        });
        nombrePro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                nombreProMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                nombreProMousePressed(evt);
            }
        });
        nombrePro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreProActionPerformed(evt);
            }
        });
        nombrePro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreProKeyTyped(evt);
            }
        });
        jPanel2.add(nombrePro);
        nombrePro.setBounds(30, 610, 350, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(30, 730, 350, 10);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(410, 820, 350, 10);

        precioUnitario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precioUnitario.setToolTipText("");
        precioUnitario.setBorder(null);
        precioUnitario.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                precioUnitarioFocusGained(evt);
            }
        });
        precioUnitario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                precioUnitarioMouseReleased(evt);
            }
        });
        precioUnitario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                precioUnitarioActionPerformed(evt);
            }
        });
        precioUnitario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                precioUnitarioKeyTyped(evt);
            }
        });
        jPanel2.add(precioUnitario);
        precioUnitario.setBounds(30, 790, 350, 30);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Clave del Producto");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(410, 580, 210, 20);

        claErr.setForeground(new java.awt.Color(255, 0, 0));
        claErr.setText("Rellenar Campo");
        jPanel2.add(claErr);
        claErr.setBounds(410, 640, 350, 16);

        cantErr.setForeground(new java.awt.Color(255, 0, 0));
        cantErr.setText("Rellenar Campo");
        jPanel2.add(cantErr);
        cantErr.setBounds(410, 820, 350, 16);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Unidad de Medida");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 670, 230, 20);

        opcCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoria" }));
        opcCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcCategoria.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcCategoriaFocusGained(evt);
            }
        });
        opcCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(opcCategoria);
        opcCategoria.setBounds(410, 470, 350, 28);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Campos");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(320, 380, 130, 24);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidad.setToolTipText("");
        cantidad.setBorder(null);
        cantidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                cantidadFocusGained(evt);
            }
        });
        cantidad.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cantidadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                cantidadMousePressed(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cantidadKeyTyped(evt);
            }
        });
        jPanel2.add(cantidad);
        cantidad.setBounds(410, 790, 350, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(30, 820, 350, 10);

        unidadM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unidadM.setToolTipText("");
        unidadM.setBorder(null);
        unidadM.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                unidadMFocusGained(evt);
            }
        });
        unidadM.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                unidadMMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                unidadMMousePressed(evt);
            }
        });
        unidadM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                unidadMActionPerformed(evt);
            }
        });
        unidadM.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                unidadMKeyTyped(evt);
            }
        });
        jPanel2.add(unidadM);
        unidadM.setBounds(30, 700, 350, 30);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Modificar Producto");
        jPanel2.add(bienvenidos);
        bienvenidos.setBounds(190, 30, 380, 47);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Magnitud de Medida");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(410, 670, 200, 20);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Precio Unitario");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 760, 180, 20);

        magErr.setForeground(new java.awt.Color(255, 0, 0));
        magErr.setText("Rellenar Campo");
        jPanel2.add(magErr);
        magErr.setBounds(410, 730, 350, 16);

        uniErr.setForeground(new java.awt.Color(255, 0, 0));
        uniErr.setText("Rellenar Campo");
        jPanel2.add(uniErr);
        uniErr.setBounds(30, 730, 350, 16);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(410, 640, 350, 10);

        opcCatErr.setForeground(new java.awt.Color(255, 0, 0));
        opcCatErr.setText("Seleccionar opción");
        jPanel2.add(opcCatErr);
        opcCatErr.setBounds(410, 500, 350, 16);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre del Producto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 580, 210, 20);

        claveP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        claveP.setToolTipText("");
        claveP.setBorder(null);
        claveP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                clavePFocusGained(evt);
            }
        });
        claveP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                clavePMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                clavePMousePressed(evt);
            }
        });
        claveP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clavePActionPerformed(evt);
            }
        });
        claveP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                clavePKeyTyped(evt);
            }
        });
        jPanel2.add(claveP);
        claveP.setBounds(410, 610, 350, 30);

        precErr.setForeground(new java.awt.Color(255, 0, 0));
        precErr.setText("Rellenar Campo");
        jPanel2.add(precErr);
        precErr.setBounds(30, 820, 350, 16);

        proErr.setForeground(new java.awt.Color(255, 0, 0));
        proErr.setText("Rellenar Campo");
        proErr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                proErrFocusGained(evt);
            }
        });
        jPanel2.add(proErr);
        proErr.setBounds(30, 640, 350, 16);

        opcProvErr.setForeground(new java.awt.Color(255, 0, 0));
        opcProvErr.setText("Seleccionar opción");
        jPanel2.add(opcProvErr);
        opcProvErr.setBounds(30, 500, 350, 16);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setText("Categoria");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(410, 440, 130, 24);

        buscaProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscaProducto.setToolTipText("");
        buscaProducto.setBorder(null);
        buscaProducto.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                buscaProductoFocusGained(evt);
            }
        });
        buscaProducto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buscaProductoMouseClicked(evt);
            }
        });
        buscaProducto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaProductoActionPerformed(evt);
            }
        });
        buscaProducto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                buscaProductoKeyTyped(evt);
            }
        });
        jPanel2.add(buscaProducto);
        buscaProducto.setBounds(220, 160, 350, 30);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Producto");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(340, 120, 130, 24);

        claveB.setText("Buscar con Clave");
        claveB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                claveBActionPerformed(evt);
            }
        });
        jPanel2.add(claveB);
        claveB.setBounds(220, 200, 130, 21);

        nombreB.setText("Buscar con Nombre");
        nombreB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreBActionPerformed(evt);
            }
        });
        jPanel2.add(nombreB);
        nombreB.setBounds(440, 200, 130, 21);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(220, 190, 350, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(120, 300, 540, 60);

        opcProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un producto" }));
        opcProductos.setToolTipText("");
        opcProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcProductos.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                opcProductosItemStateChanged(evt);
            }
        });
        opcProductos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcProductosActionPerformed(evt);
            }
        });
        jPanel2.add(opcProductos);
        opcProductos.setBounds(220, 260, 350, 28);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreProActionPerformed
    {//GEN-HEADEREND:event_nombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProActionPerformed

    private void nombreProKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreProKeyTyped
    {//GEN-HEADEREND:event_nombreProKeyTyped
        Validaciones.va(evt, 30, nombrePro.getText());
    }//GEN-LAST:event_nombreProKeyTyped

    private void precioUnitarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_precioUnitarioActionPerformed
    {//GEN-HEADEREND:event_precioUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioUnitarioActionPerformed

    private void precioUnitarioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioUnitarioKeyTyped
    {//GEN-HEADEREND:event_precioUnitarioKeyTyped
        Validaciones.validaPrecios(evt, 10, precioUnitario.getText());
    }//GEN-LAST:event_precioUnitarioKeyTyped

    private void unidadMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_unidadMActionPerformed
    {//GEN-HEADEREND:event_unidadMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadMActionPerformed

    private void unidadMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_unidadMKeyTyped
    {//GEN-HEADEREND:event_unidadMKeyTyped
        Validaciones.va(evt, 2, unidadM.getText());
    }//GEN-LAST:event_unidadMKeyTyped

    private void magnitudMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_magnitudMActionPerformed
    {//GEN-HEADEREND:event_magnitudMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_magnitudMActionPerformed

    private void magnitudMKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_magnitudMKeyTyped
    {//GEN-HEADEREND:event_magnitudMKeyTyped
        Validaciones.validaEntero(evt, 5, magnitudM.getText());
    }//GEN-LAST:event_magnitudMKeyTyped

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cantidadActionPerformed
    {//GEN-HEADEREND:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cantidadKeyTyped
    {//GEN-HEADEREND:event_cantidadKeyTyped
        Validaciones.validaEntero(evt, 5, cantidad.getText());
    }//GEN-LAST:event_cantidadKeyTyped

    private void opcProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcProveedorActionPerformed
    {//GEN-HEADEREND:event_opcProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcProveedorActionPerformed

    private void opcCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcCategoriaActionPerformed
    {//GEN-HEADEREND:event_opcCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcCategoriaActionPerformed

    private void agregarPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseEntered
    {//GEN-HEADEREND:event_agregarPMouseEntered
        agregarP.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_agregarPMouseEntered

    private void agregarPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseExited
    {//GEN-HEADEREND:event_agregarPMouseExited
        agregarP.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_agregarPMouseExited

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarPActionPerformed
    {//GEN-HEADEREND:event_agregarPActionPerformed
        int opc = 0;
        if (opcProveedor.getItemCount() == 1)
        {
            opc = 1;
        }
        if (opcCategoria.getItemCount() == 1)
        {
            if (opc == 1)
            {
                opc = 3;
            } else
            {
                opc = 2;
            }
        }
        if (opc == 0)
        {
            boolean b = false;
            if (nombrePro.getText().isEmpty())
            {
                b = true;
                proErr.setText("Rellenar Campo");
                proErr.setVisible(true);
            }
            if (claveP.getText().isEmpty())
            {
                b = true;
                claErr.setText("Rellenar Campo");
                claErr.setVisible(true);
            }
            if (unidadM.getText().isEmpty())
            {
                b = true;
                uniErr.setText("Rellenar Campo");
                uniErr.setVisible(true);
            }
            if (magnitudM.getText().isEmpty())
            {
                b = true;
                magErr.setText("Rellenar Campo");
                magErr.setVisible(true);
            }
            if (precioUnitario.getText().isEmpty())
            {
                b = true;
                precErr.setText("Rellenar Campo");
                precErr.setVisible(true);
            }
            if (cantidad.getText().isEmpty())
            {
                b = true;
                cantErr.setText("Rellenar Campo");
                cantErr.setVisible(true);
            }
            if (opcCategoria.getSelectedIndex() == 0)
            {
                b = true;
                opcCatErr.setVisible(true);
            }
            if (opcProveedor.getSelectedIndex() == 0)
            {
                b = true;
                opcProvErr.setVisible(true);
            }
            if (!b)
            {
                String valores = "id = " + claveP.getText() + ", "
                        + "nombre = '" + nombrePro.getText() + "', "
                        + "unidadMed = '" + unidadM.getText() + "', "
                        + "magnitudMed = " + magnitudM.getText() + ", "
                        + "precio = " + precioUnitario.getText() + " ,"
                        + "cantidad = " + cantidad.getText() + ", "
                        + "id_Proveedor = " + (opcProveedor.getSelectedItem().toString().split(":")[0] + ", "
                        + "id_Categoria = " + (opcCategoria.getSelectedItem().toString().split(":")[0]));
                String sentencia = "id = " + opcProductos.getSelectedItem().toString().split(":")[0];
                if (CRUD.update("Producto", sentencia, valores)==1)
                {
                    nombrePro.setText("");
                    claveP.setText("");
                    unidadM.setText("");
                    magnitudM.setText("");
                    precioUnitario.setText("");
                    cantidad.setText("");
                    opcProveedor.setSelectedIndex(0);
                    opcCategoria.setSelectedIndex(0);
                }

            } else
            {
                JOptionPane.showMessageDialog(null, "Producto NO REGISTRADO");
            }
        } else
        {
            if (opc == 3)
            {
                JOptionPane.showMessageDialog(null, "NO datos CATEGORIAS/PROVEEDORES");
            } else if (opc == 2)
            {
                JOptionPane.showMessageDialog(null, "NO datos de CATEGORIAS");
                opcCatErr.setText("No datos");
                opcCatErr.setVisible(true);
            } else
            {
                JOptionPane.showMessageDialog(null, "NO datos de PROVEEDORES");
                opcProvErr.setText("No datos");
                opcProvErr.setVisible(true);
            }
        }
    }//GEN-LAST:event_agregarPActionPerformed

    private void agregarPMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseClicked
    {//GEN-HEADEREND:event_agregarPMouseClicked

    }//GEN-LAST:event_agregarPMouseClicked

    private void nombreProMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombreProMouseClicked
    {//GEN-HEADEREND:event_nombreProMouseClicked

    }//GEN-LAST:event_nombreProMouseClicked

    private void clavePMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clavePMouseClicked
    {//GEN-HEADEREND:event_clavePMouseClicked

    }//GEN-LAST:event_clavePMouseClicked

    private void clavePActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clavePActionPerformed
    {//GEN-HEADEREND:event_clavePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clavePActionPerformed

    private void clavePKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_clavePKeyTyped
    {//GEN-HEADEREND:event_clavePKeyTyped
        Validaciones.validaEntero(evt, 13, claveP.getText());
    }//GEN-LAST:event_clavePKeyTyped

    private void unidadMMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_unidadMMouseClicked
    {//GEN-HEADEREND:event_unidadMMouseClicked

    }//GEN-LAST:event_unidadMMouseClicked

    private void magnitudMMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_magnitudMMouseClicked
    {//GEN-HEADEREND:event_magnitudMMouseClicked

    }//GEN-LAST:event_magnitudMMouseClicked

    private void precioUnitarioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMouseClicked
    {//GEN-HEADEREND:event_precioUnitarioMouseClicked

    }//GEN-LAST:event_precioUnitarioMouseClicked

    private void cantidadMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cantidadMouseClicked
    {//GEN-HEADEREND:event_cantidadMouseClicked

    }//GEN-LAST:event_cantidadMouseClicked

    private void nombreProMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_nombreProMousePressed
    {//GEN-HEADEREND:event_nombreProMousePressed

    }//GEN-LAST:event_nombreProMousePressed

    private void clavePMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clavePMousePressed
    {//GEN-HEADEREND:event_clavePMousePressed

    }//GEN-LAST:event_clavePMousePressed

    private void unidadMMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_unidadMMousePressed
    {//GEN-HEADEREND:event_unidadMMousePressed

    }//GEN-LAST:event_unidadMMousePressed

    private void magnitudMMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_magnitudMMousePressed
    {//GEN-HEADEREND:event_magnitudMMousePressed

    }//GEN-LAST:event_magnitudMMousePressed

    private void precioUnitarioMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMouseReleased
    {//GEN-HEADEREND:event_precioUnitarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_precioUnitarioMouseReleased

    private void precioUnitarioMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_precioUnitarioMousePressed
    {//GEN-HEADEREND:event_precioUnitarioMousePressed

    }//GEN-LAST:event_precioUnitarioMousePressed

    private void cantidadMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cantidadMousePressed
    {//GEN-HEADEREND:event_cantidadMousePressed

    }//GEN-LAST:event_cantidadMousePressed

    private void nombreProFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombreProFocusGained
    {//GEN-HEADEREND:event_nombreProFocusGained
        proErr.setVisible(false);
    }//GEN-LAST:event_nombreProFocusGained

    private void clavePFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_clavePFocusGained
    {//GEN-HEADEREND:event_clavePFocusGained
        claErr.setVisible(false);
    }//GEN-LAST:event_clavePFocusGained

    private void unidadMFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_unidadMFocusGained
    {//GEN-HEADEREND:event_unidadMFocusGained
        uniErr.setVisible(false);
    }//GEN-LAST:event_unidadMFocusGained

    private void magnitudMFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_magnitudMFocusGained
    {//GEN-HEADEREND:event_magnitudMFocusGained
        magErr.setVisible(false);
    }//GEN-LAST:event_magnitudMFocusGained

    private void precioUnitarioFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_precioUnitarioFocusGained
    {//GEN-HEADEREND:event_precioUnitarioFocusGained
        precErr.setVisible(false);
    }//GEN-LAST:event_precioUnitarioFocusGained

    private void cantidadFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_cantidadFocusGained
    {//GEN-HEADEREND:event_cantidadFocusGained
        cantErr.setVisible(false);
    }//GEN-LAST:event_cantidadFocusGained

    private void opcProveedorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcProveedorFocusGained
    {//GEN-HEADEREND:event_opcProveedorFocusGained
        opcProvErr.setVisible(false);
    }//GEN-LAST:event_opcProveedorFocusGained

    private void opcCategoriaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcCategoriaFocusGained
    {//GEN-HEADEREND:event_opcCategoriaFocusGained
        opcCatErr.setVisible(false);
    }//GEN-LAST:event_opcCategoriaFocusGained

    private void proErrFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_proErrFocusGained
    {//GEN-HEADEREND:event_proErrFocusGained

    }//GEN-LAST:event_proErrFocusGained

    private void buscaProductoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buscaProductoFocusGained
    {//GEN-HEADEREND:event_buscaProductoFocusGained

    }//GEN-LAST:event_buscaProductoFocusGained

    private void buscaProductoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaProductoMouseClicked
    {//GEN-HEADEREND:event_buscaProductoMouseClicked

    }//GEN-LAST:event_buscaProductoMouseClicked

    private void buscaProductoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaProductoActionPerformed
    {//GEN-HEADEREND:event_buscaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProductoActionPerformed

    private void buscaProductoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaProductoKeyTyped
    {//GEN-HEADEREND:event_buscaProductoKeyTyped
        if (estado)
        {
            Validaciones.validaEntero(evt, 13, buscaProducto.getText());
        } else
        {
            Validaciones.validaLetra(evt, 20, buscaProducto.getText());
        }
    }//GEN-LAST:event_buscaProductoKeyTyped

    private void claveBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_claveBActionPerformed
    {//GEN-HEADEREND:event_claveBActionPerformed
        buscaProducto.setText("");
        if (claveB.isSelected())
        {
            buscaProducto.setText("");
            estado = true;
            if (nombreB.isSelected())
            {
                nombreB.setSelected(false);
            }
            buscaProducto.setEnabled(true);
        } else
        {
            if (nombreB.isSelected())
            {
                buscaProducto.setEnabled(true);
            } else
            {
                buscaProducto.setEnabled(false);
            }
        }
    }//GEN-LAST:event_claveBActionPerformed

    private void nombreBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreBActionPerformed
    {//GEN-HEADEREND:event_nombreBActionPerformed
        buscaProducto.setText("");
        if (nombreB.isSelected())
        {
            estado = false;
            if (claveB.isSelected())
            {
                claveB.setSelected(false);
            }
            buscaProducto.setEnabled(true);
        } else
        {
            if (claveB.isSelected())
            {
                buscaProducto.setEnabled(true);
            } else
            {
                buscaProducto.setEnabled(false);
            }
        }
    }//GEN-LAST:event_nombreBActionPerformed

    private void opcProductosItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_opcProductosItemStateChanged
    {//GEN-HEADEREND:event_opcProductosItemStateChanged

    }//GEN-LAST:event_opcProductosItemStateChanged

    private void opcProductosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcProductosActionPerformed
    {//GEN-HEADEREND:event_opcProductosActionPerformed
        jScrollPane1.setVisible(false);
        if (opcProductos.getSelectedIndex() != 0 && opcProductos.getItemCount() > 1)
        {
            jScrollPane1.setVisible(true);
            jTable1.setRowHeight(32);
            m2 = new DefaultTableModel();
            String c2[] =
            {
                "Nombre", "Precio", "Cantidad", "Magintud", "Unidad", "Proveedor", "Categoria"
            };
            m2.setColumnIdentifiers(c2);
            jTable1.setModel(m2);
            try
            {
                String sentencia = "id=" + (opcProductos.getSelectedItem().toString().split(":")[0]);
                ResultSet rat = CRUD.read("producto", "*", "WHERE " + sentencia);
                rat.next();
                ResultSet ratProv = CRUD.read("proveedor", "*", "WHERE id = " + rat.getString("id_Proveedor"));
                ratProv.next();
                ResultSet ratCat = CRUD.read("categoria", "*", "WHERE id = " + rat.getString("id_Categoria"));
                ratCat.next();
                String f[] =
                {
                    rat.getString("nombre"), rat.getString("precio"),
                    rat.getString("cantidad"), rat.getString("magnitudMed"),
                    rat.getString("unidadMed"), ratProv.getString("nombre"),
                    ratCat.getString("nombre")
                };
                m2.addRow(f);
                nombrePro.setText(rat.getString("nombre"));
                claveP.setText(rat.getString("id"));
                unidadM.setText(rat.getString("unidadMed"));
                magnitudM.setText(rat.getString("magnitudMed"));
                precioUnitario.setText(rat.getString("precio"));
                cantidad.setText(rat.getString("cantidad"));
                buscaItem(opcProveedor, ratProv.getInt("id"));
                buscaItem(opcCategoria, ratCat.getInt("id"));
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
            jTable1.setEnabled(false);
        }
    }//GEN-LAST:event_opcProductosActionPerformed

    public void buscaItem(JComboBox jb, int id)
    {
        for (int i = 0; i < jb.getItemCount(); i++)
        {
            if (jb.getItemAt(i).toString().split(":")[0].equals(String.valueOf(id)))
            {
                jb.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarP;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JTextField buscaProducto;
    private javax.swing.JLabel cantErr;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel claErr;
    private javax.swing.JRadioButton claveB;
    private javax.swing.JTextField claveP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel magErr;
    private javax.swing.JTextField magnitudM;
    private javax.swing.JRadioButton nombreB;
    private javax.swing.JTextField nombrePro;
    private javax.swing.JLabel opcCatErr;
    private javax.swing.JComboBox<String> opcCategoria;
    private javax.swing.JComboBox<String> opcProductos;
    private javax.swing.JLabel opcProvErr;
    private javax.swing.JComboBox<String> opcProveedor;
    private javax.swing.JLabel precErr;
    private javax.swing.JTextField precioUnitario;
    private javax.swing.JLabel proErr;
    private javax.swing.JLabel uniErr;
    private javax.swing.JTextField unidadM;
    // End of variables declaration//GEN-END:variables
}
