/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicButtonUI;
import herramientas.TextPrompt;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author jonas
 */
public class ModificarCategoria extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    public ModificarCategoria()
    {
        initComponents();
        opcCategoria.setUI(Propiedades.createUI(this));
        agregarP.setUI(new BasicButtonUI());
        agregarP.setBorder(new RoundedBorder(10));
        ResultSet rat2 = CRUD.read("categoria", "*", "ORDER BY id");
        cargarComboBox(rat2, opcCategoria);
        campos();
        opcCatErr.setVisible(false);
        catErr.setVisible(false);
        listenersBuscadores();
    }
    
    public void campos()
    {
        TextPrompt buscCateg = new TextPrompt("Ingrese Categoria", buscaCategoria);
        TextPrompt catNP = new TextPrompt("ABCDEF", cat);
    }
    
    public void cargarComboBox(ResultSet rat, JComboBox jcb)
    {
        if (rat != null)
        {
            try
            {
                while (rat.next())
                {
//                    jcb.addItem(rat.getString("nombre"));
                    jcb.addItem(rat.getString("id") + ":  " + rat.getString("nombre"));
                }
            } catch (Exception e)
            {
                System.out.println(e.toString() + "    mm");
            }
        } else
        {
            
        }
    }

    // Carga de nuevo los productos a el comboBox
    public void consultaCombo(JComboBox jb, String tabla, String sentencia)
    {
        jb.removeAllItems();
        jb.addItem("Seleccione un producto");
        ResultSet rat = CRUD.read(tabla, "*", sentencia + " ORDER BY id");
        cargarComboBox(rat, jb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        opcCategoria = new javax.swing.JComboBox<>();
        agregarP = new javax.swing.JButton();
        opcCatErr = new javax.swing.JLabel();
        buscaCategoria = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cat = new javax.swing.JTextField();
        catErr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos.setText("Modificar Categoria");
        add(bienvenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 370, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setText("Categoria");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 130, -1));

        opcCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoria" }));
        opcCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcCategoria.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                opcCategoriaFocusGained(evt);
            }
        });
        opcCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opcCategoriaActionPerformed(evt);
            }
        });
        add(opcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 350, -1));

        agregarP.setBackground(new java.awt.Color(33, 12, 255));
        agregarP.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregarP.setForeground(new java.awt.Color(255, 255, 255));
        agregarP.setText("Modificar");
        agregarP.setBorder(null);
        agregarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarP.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                agregarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarPMouseExited(evt);
            }
        });
        agregarP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarPActionPerformed(evt);
            }
        });
        add(agregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 140, 50));

        opcCatErr.setForeground(new java.awt.Color(255, 0, 0));
        opcCatErr.setText("Seleccionar opción");
        add(opcCatErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 350, -1));

        buscaCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscaCategoria.setToolTipText("");
        buscaCategoria.setBorder(null);
        buscaCategoria.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                buscaCategoriaFocusGained(evt);
            }
        });
        buscaCategoria.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buscaCategoriaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                buscaCategoriaMousePressed(evt);
            }
        });
        buscaCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaCategoriaActionPerformed(evt);
            }
        });
        buscaCategoria.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                buscaCategoriaKeyTyped(evt);
            }
        });
        add(buscaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 350, 30));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 350, 10));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Campo");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 200, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 300, 10));

        cat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cat.setToolTipText("");
        cat.setBorder(null);
        cat.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                catFocusGained(evt);
            }
        });
        cat.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                catMouseClicked(evt);
            }
        });
        cat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                catActionPerformed(evt);
            }
        });
        cat.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                catKeyTyped(evt);
            }
        });
        add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 300, 30));

        catErr.setForeground(new java.awt.Color(255, 0, 0));
        catErr.setText("Rellenar Campo");
        add(catErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 300, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de la Categoria");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoAtras.png"))); // NOI18N
        atras.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                atrasMouseExited(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atrasActionPerformed(evt);
            }
        });
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void opcCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcCategoriaActionPerformed
    {//GEN-HEADEREND:event_opcCategoriaActionPerformed
        if (opcCategoria.getSelectedIndex() != 0 && opcCategoria.getItemCount() > 1)
        {
            ResultSet rat = CRUD.read("Categoria", "*", "WHERE id=" + opcCategoria.getSelectedItem().toString().split(":")[0]);
            try
            {
                rat.next();
                cat.setText(rat.getString("nombre"));
            } catch (Exception e)
            {
                System.out.println(e.toString());
            }
        } else
        {
            cat.setText("");
        }
    }//GEN-LAST:event_opcCategoriaActionPerformed

    private void agregarPMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseEntered
    {//GEN-HEADEREND:event_agregarPMouseEntered
        agregarP.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_agregarPMouseEntered

    private void agregarPMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseExited
    {//GEN-HEADEREND:event_agregarPMouseExited
        agregarP.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_agregarPMouseExited

    private void agregarPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarPActionPerformed
    {//GEN-HEADEREND:event_agregarPActionPerformed
        boolean b = false;
        if (opcCategoria.getSelectedIndex() == 0)
        {
            b = true;
            opcCatErr.setVisible(true);
            JOptionPane.showMessageDialog(null, "No se ha seleccionado Categoria");
        } else
        {
            if (!b)
            {
                Object[] options =
                {
                    "Sí", "Cancelar"
                };
                if (JOptionPane.showOptionDialog(null,
                        "¿Seguro que desea actualizar?",
                        "Confirmación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]) == 0)
                {
                    int c = CRUD.update("Categoria", "id=" + opcCategoria.getSelectedItem().toString().split(":")[0],
                            "nombre = '" + cat.getText() + "'");
                    switch (c)
                    {
                        case 0:
                            consultaCombo(opcCategoria, "Categoria", "");
                            cat.setText("");
                            buscaCategoria.setText("");
                            buscaCategoria.setEnabled(false);
                            JOptionPane.showMessageDialog(null, "Categoria ACTUALIZADA");
                            break;
                        case 2:
                            JOptionPane.showMessageDialog(null, "Categoria NO ACTUALIZADA \n Los datos de la "
                                    + "Categoria ya se encuentran en el sistema"
                                    + "\n (Nombre)");
                            break;
                    }
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "Categoria NO ACTUALIZADA");
            }
        }
        

    }//GEN-LAST:event_agregarPActionPerformed

    private void agregarPMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarPMouseClicked
    {//GEN-HEADEREND:event_agregarPMouseClicked

    }//GEN-LAST:event_agregarPMouseClicked

    private void opcCategoriaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_opcCategoriaFocusGained
    {//GEN-HEADEREND:event_opcCategoriaFocusGained
        opcCatErr.setVisible(false);
    }//GEN-LAST:event_opcCategoriaFocusGained

    private void buscaCategoriaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_buscaCategoriaFocusGained
    {//GEN-HEADEREND:event_buscaCategoriaFocusGained
        opcCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_buscaCategoriaFocusGained

    private void buscaCategoriaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaCategoriaMouseClicked
    {//GEN-HEADEREND:event_buscaCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaMouseClicked

    private void buscaCategoriaMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscaCategoriaMousePressed
    {//GEN-HEADEREND:event_buscaCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaMousePressed

    private void buscaCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaCategoriaActionPerformed
    {//GEN-HEADEREND:event_buscaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCategoriaActionPerformed

    private void buscaCategoriaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_buscaCategoriaKeyTyped
    {//GEN-HEADEREND:event_buscaCategoriaKeyTyped
        Validaciones.validaLetra(evt, 20, buscaCategoria.getText());
    }//GEN-LAST:event_buscaCategoriaKeyTyped

    private void catFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_catFocusGained
    {//GEN-HEADEREND:event_catFocusGained
        catErr.setVisible(false);
    }//GEN-LAST:event_catFocusGained

    private void catMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_catMouseClicked
    {//GEN-HEADEREND:event_catMouseClicked

    }//GEN-LAST:event_catMouseClicked

    private void catActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catActionPerformed
    {//GEN-HEADEREND:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void catKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_catKeyTyped
    {//GEN-HEADEREND:event_catKeyTyped
        Validaciones.validaLetra(evt, 20, cat.getText());
    }//GEN-LAST:event_catKeyTyped

    private void atrasMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseEntered
    {//GEN-HEADEREND:event_atrasMouseEntered
        atras.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_atrasMouseEntered

    private void atrasMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_atrasMouseExited
    {//GEN-HEADEREND:event_atrasMouseExited
        atras.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_atrasMouseExited

    private void atrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atrasActionPerformed
    {//GEN-HEADEREND:event_atrasActionPerformed
        Inventario.pintarOpc(new GestionCategorias());
    }//GEN-LAST:event_atrasActionPerformed
    
    public void listenersBuscadores()
    {
        buscaCategoria.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                // Acción cuando se inserta texto
                if (buscaCategoria.getText().isEmpty())
                {
                    consultaCombo(opcCategoria, "Categoria", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaCategoria.getText() + "%'";
                    consultaCombo(opcCategoria, "Categoria", sentencia);
                }
            }
            
            @Override
            public void removeUpdate(DocumentEvent e)
            {
                // Acción cuando se elimina texto
                if (buscaCategoria.getText().isEmpty())
                {
                    consultaCombo(opcCategoria, "Categoria", "");
                } else
                {
                    String sentencia = "WHERE nombre LIKE '%" + buscaCategoria.getText() + "%'";
                    consultaCombo(opcCategoria, "Categoria", sentencia);
                }
            }
            
            @Override
            public void changedUpdate(DocumentEvent e)
            {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarP;
    private javax.swing.JButton atras;
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JTextField buscaCategoria;
    private javax.swing.JTextField cat;
    private javax.swing.JLabel catErr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel opcCatErr;
    private javax.swing.JComboBox<String> opcCategoria;
    // End of variables declaration//GEN-END:variables
}
