/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonas
 */
public class RegistroV extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    DefaultTableModel m2 = new DefaultTableModel();
    int bandera = 0;
    Color colorD = new Color(33, 12, 255);
    Color colorS = new Color(30, 161, 255);

    public RegistroV()
    {
        initComponents();
        proFec.setUI(new BasicButtonUI());
        producto.setUI(new BasicButtonUI());
        ventas.setUI(new BasicButtonUI());
        fecha.setUI(new BasicButtonUI());
        proVen.setUI(new BasicButtonUI());
        colorearB(2);
        actualizarTabla();
    }

    public void actualizarTabla()
    {
        jScrollPane1.setVisible(true);
        jTable1.setRowHeight(32);
        m2 = new DefaultTableModel();
        String c2[] =
        {
            "ID (TICKET)", "Fecha de la venta", "Pago total"
        };
        m2.setColumnIdentifiers(c2);
        jTable1.setModel(m2);
        try
        {
            ResultSet rat = CRUD.read("ventas", "*", "");
            while (rat.next())
            {
                String f[] =
                {
                    rat.getString("id"), rat.getString("fechaHora"), rat.getString("total_venta")
                };
                m2.addRow(f);

            }

        } catch (Exception e)
        {
            System.out.println("asdasaaaaaaaaaaaaa");
        }
        jTable1.setEnabled(false);
        if (!(jTable1.getRowCount() >= 1))
        {
            jPanel1.remove(jScrollPane1);
            jPanel1.setBackground(new Color(204, 204, 204));
            JLabel l = new JLabel();
            l.setText("No hay ventas");
            l.setBounds(0, 0, 680, 280);
            l.setVerticalAlignment(0);
            l.setHorizontalAlignment(0);
            Font f = new Font(this.getFont().getName(), 3, 48);
            l.setFont(f);
            jPanel1.add(l);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ventas = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        proFec = new javax.swing.JButton();
        fecha = new javax.swing.JButton();
        proVen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setText("Registro Ventas");
        add(bienvenidos);
        bienvenidos.setBounds(270, 10, 280, 44);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        ventas.setBackground(new java.awt.Color(33, 12, 255));
        ventas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ventas.setForeground(new java.awt.Color(255, 255, 255));
        ventas.setText("Consulta ventas general");
        ventas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                ventasMouseExited(evt);
            }
        });
        ventas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ventasActionPerformed(evt);
            }
        });
        jPanel2.add(ventas);
        ventas.setBounds(265, 0, 265, 50);

        producto.setBackground(new java.awt.Color(33, 12, 255));
        producto.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setText("Consultar por producto");
        producto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                productoMouseExited(evt);
            }
        });
        producto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                productoActionPerformed(evt);
            }
        });
        jPanel2.add(producto);
        producto.setBounds(530, 0, 265, 50);

        proFec.setBackground(new java.awt.Color(33, 12, 255));
        proFec.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        proFec.setForeground(new java.awt.Color(255, 255, 255));
        proFec.setText("Consultar por Producto/Fecha");
        proFec.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                proFecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                proFecMouseExited(evt);
            }
        });
        proFec.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                proFecActionPerformed(evt);
            }
        });
        jPanel2.add(proFec);
        proFec.setBounds(394, 50, 320, 50);

        fecha.setBackground(new java.awt.Color(33, 12, 255));
        fecha.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Consultar por fecha");
        fecha.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                fechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                fechaMouseExited(evt);
            }
        });
        fecha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fechaActionPerformed(evt);
            }
        });
        jPanel2.add(fecha);
        fecha.setBounds(0, 0, 265, 50);

        proVen.setBackground(new java.awt.Color(33, 12, 255));
        proVen.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        proVen.setForeground(new java.awt.Color(255, 255, 255));
        proVen.setText("Consultar por Producto/Venta");
        proVen.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                proVenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                proVenMouseExited(evt);
            }
        });
        proVen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                proVenActionPerformed(evt);
            }
        });
        jPanel2.add(proVen);
        proVen.setBounds(70, 50, 324, 50);

        add(jPanel2);
        jPanel2.setBounds(0, 60, 795, 110);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 680, 370);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(50, 40, 680, 370);

        add(jPanel3);
        jPanel3.setBounds(0, 190, 795, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void proFecMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proFecMouseEntered
    {//GEN-HEADEREND:event_proFecMouseEntered
        if (proFec.getBackground().equals(colorD))
        {
            proFec.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_proFecMouseEntered

    private void proFecMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proFecMouseExited
    {//GEN-HEADEREND:event_proFecMouseExited
        if (proFec.getBackground().equals(colorS) && bandera != 5)
        {
            proFec.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_proFecMouseExited

    private void proFecActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proFecActionPerformed
    {//GEN-HEADEREND:event_proFecActionPerformed
        pintarOpc(new ConsultarVPorProdFecha());
        bandera = 5;
        colorearB(bandera);
    }//GEN-LAST:event_proFecActionPerformed

    private void ventasMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ventasMouseEntered
    {//GEN-HEADEREND:event_ventasMouseEntered
        if (ventas.getBackground().equals(colorD))
        {
            ventas.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_ventasMouseEntered

    private void ventasMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ventasMouseExited
    {//GEN-HEADEREND:event_ventasMouseExited
        if (ventas.getBackground().equals(colorS) && bandera != 2)
        {
            ventas.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_ventasMouseExited

    private void ventasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ventasActionPerformed
    {//GEN-HEADEREND:event_ventasActionPerformed
        MenuOpciones.pintarOpc(new RegistroV());
        bandera = 2;
        colorearB(bandera);
    }//GEN-LAST:event_ventasActionPerformed

    private void productoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_productoMouseEntered
    {//GEN-HEADEREND:event_productoMouseEntered
        if (producto.getBackground().equals(colorD))
        {
            producto.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_productoMouseEntered

    private void productoMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_productoMouseExited
    {//GEN-HEADEREND:event_productoMouseExited
        if (producto.getBackground().equals(colorS) && bandera != 3)
        {
            producto.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_productoMouseExited

    private void productoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_productoActionPerformed
    {//GEN-HEADEREND:event_productoActionPerformed
        pintarOpc(new ConsultarVPorProd());
        bandera = 3;
        colorearB(bandera);
    }//GEN-LAST:event_productoActionPerformed

    private void fechaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fechaMouseEntered
    {//GEN-HEADEREND:event_fechaMouseEntered
        if (fecha.getBackground().equals(colorD))
        {
            fecha.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_fechaMouseEntered

    private void fechaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fechaMouseExited
    {//GEN-HEADEREND:event_fechaMouseExited
        if (fecha.getBackground().equals(colorS) && bandera != 1)
        {
            fecha.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_fechaMouseExited

    private void fechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fechaActionPerformed
    {//GEN-HEADEREND:event_fechaActionPerformed
        pintarOpc(new ConsultarVPorFecha());
        bandera = 1;
        colorearB(bandera);
    }//GEN-LAST:event_fechaActionPerformed

    private void proVenMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proVenMouseEntered
    {//GEN-HEADEREND:event_proVenMouseEntered
        if (proVen.getBackground().equals(colorD))
        {
            proVen.setBackground(new Color(30, 161, 255));
        }
    }//GEN-LAST:event_proVenMouseEntered

    private void proVenMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_proVenMouseExited
    {//GEN-HEADEREND:event_proVenMouseExited
        if (proVen.getBackground().equals(colorS) && bandera != 4)
        {
            proVen.setBackground(new Color(33, 12, 255));
        }
    }//GEN-LAST:event_proVenMouseExited

    private void proVenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proVenActionPerformed
    {//GEN-HEADEREND:event_proVenActionPerformed
        pintarOpc(new ConsultarVPorProdVenta());
        bandera = 4;
        colorearB(bandera);
    }//GEN-LAST:event_proVenActionPerformed
    public void colorearB(int n)
    {
        switch (n)
        {
            case 1:
                fecha.setBackground(colorS);
                ventas.setBackground(colorD);
                producto.setBackground(colorD);
                proVen.setBackground(colorD);
                proFec.setBackground(colorD);
                break;
            case 2:
                fecha.setBackground(colorD);
                ventas.setBackground(colorS);
                producto.setBackground(colorD);
                proVen.setBackground(colorD);
                proFec.setBackground(colorD);
                break;
            case 3:
                fecha.setBackground(colorD);
                ventas.setBackground(colorD);
                producto.setBackground(colorS);
                proVen.setBackground(colorD);
                proFec.setBackground(colorD);
                break;
            case 4:
                fecha.setBackground(colorD);
                ventas.setBackground(colorD);
                producto.setBackground(colorD);
                proVen.setBackground(colorS);
                proFec.setBackground(colorD);
                break;
            case 5:
                fecha.setBackground(colorD);
                ventas.setBackground(colorD);
                producto.setBackground(colorD);
                proVen.setBackground(colorD);
                proFec.setBackground(colorS);
                break;
            default:
                break;
        }
    }

    public static void pintarOpc(JPanel p)
    {
        p.setSize(795, 610);
        p.setLocation(0, 0);
        jPanel3.removeAll();
        jPanel3.add(p, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JButton fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton proFec;
    private javax.swing.JButton proVen;
    private javax.swing.JButton producto;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
