/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import java.awt.Color;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author jonas
 */
public class RegistroVentas extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    public RegistroVentas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bienvenidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bienvenidos.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos.setText("Registro Ventas");
        add(bienvenidos);
        bienvenidos.setBounds(410, 20, 190, 47);

        jLabel1.setText("Producto");
        add(jLabel1);
        jLabel1.setBounds(140, 140, 80, 20);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(140, 160, 80, 22);

        jLabel2.setText("Cantidad");
        add(jLabel2);
        jLabel2.setBounds(260, 140, 48, 16);

        jTextField2.setText("jTextField2");
        add(jTextField2);
        jTextField2.setBounds(260, 160, 71, 22);

        jLabel3.setText("Fecha");
        add(jLabel3);
        jLabel3.setBounds(380, 140, 31, 16);

        jTextField3.setText("jTextField3");
        add(jTextField3);
        jTextField3.setBounds(380, 160, 71, 22);

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4);
        jTextField4.setBounds(490, 160, 71, 22);

        jLabel4.setText("PrecioTotal");
        add(jLabel4);
        jLabel4.setBounds(490, 140, 90, 16);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(610, 160, 73, 23);

        jLabel5.setText("Producto");
        add(jLabel5);
        jLabel5.setBounds(140, 200, 80, 20);

        jTextField5.setText("jTextField1");
        add(jTextField5);
        jTextField5.setBounds(140, 220, 80, 22);

        jLabel6.setText("Cantidad");
        add(jLabel6);
        jLabel6.setBounds(260, 200, 48, 16);

        jTextField6.setText("jTextField2");
        add(jTextField6);
        jTextField6.setBounds(260, 220, 71, 22);

        jLabel7.setText("Fecha");
        add(jLabel7);
        jLabel7.setBounds(380, 200, 31, 16);

        jTextField7.setText("jTextField3");
        add(jTextField7);
        jTextField7.setBounds(380, 220, 71, 22);

        jTextField8.setText("jTextField4");
        jTextField8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8);
        jTextField8.setBounds(490, 220, 71, 22);

        jLabel8.setText("PrecioTotal");
        add(jLabel8);
        jLabel8.setBounds(490, 200, 90, 16);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(610, 220, 73, 23);

        jButton3.setText("Comprar");
        add(jButton3);
        jButton3.setBounds(610, 460, 77, 23);

        jButton4.setText("Cancelar");
        add(jButton4);
        jButton4.setBounds(493, 460, 100, 23);

        jLabel9.setText("Producto");
        add(jLabel9);
        jLabel9.setBounds(140, 260, 80, 20);

        jTextField9.setText("jTextField1");
        add(jTextField9);
        jTextField9.setBounds(140, 280, 80, 22);

        jLabel10.setText("Cantidad");
        add(jLabel10);
        jLabel10.setBounds(260, 260, 48, 16);

        jTextField10.setText("jTextField2");
        add(jTextField10);
        jTextField10.setBounds(260, 280, 71, 22);

        jLabel11.setText("Fecha");
        add(jLabel11);
        jLabel11.setBounds(380, 260, 31, 16);

        jTextField11.setText("jTextField3");
        add(jTextField11);
        jTextField11.setBounds(380, 280, 71, 22);

        jTextField12.setText("jTextField4");
        jTextField12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12);
        jTextField12.setBounds(490, 280, 71, 22);

        jLabel12.setText("PrecioTotal");
        add(jLabel12);
        jLabel12.setBounds(490, 260, 90, 16);

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(610, 280, 73, 23);

        jLabel13.setText("Producto");
        add(jLabel13);
        jLabel13.setBounds(140, 320, 80, 20);

        jTextField13.setText("jTextField1");
        add(jTextField13);
        jTextField13.setBounds(140, 340, 80, 22);

        jLabel14.setText("Cantidad");
        add(jLabel14);
        jLabel14.setBounds(260, 320, 48, 16);

        jTextField14.setText("jTextField2");
        add(jTextField14);
        jTextField14.setBounds(260, 340, 71, 22);

        jLabel15.setText("Fecha");
        add(jLabel15);
        jLabel15.setBounds(380, 320, 31, 16);

        jTextField15.setText("jTextField3");
        add(jTextField15);
        jTextField15.setBounds(380, 340, 71, 22);

        jTextField16.setText("jTextField4");
        jTextField16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField16ActionPerformed(evt);
            }
        });
        add(jTextField16);
        jTextField16.setBounds(490, 340, 71, 22);

        jLabel16.setText("PrecioTotal");
        add(jLabel16);
        jLabel16.setBounds(490, 320, 90, 16);

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(610, 340, 72, 23);

        jLabel17.setText("ID_VETA32");
        add(jLabel17);
        jLabel17.setBounds(70, 280, 60, 16);

        jLabel18.setText("ID_VETA32");
        add(jLabel18);
        jLabel18.setBounds(70, 160, 60, 16);

        jLabel19.setText("ID_VETA32");
        add(jLabel19);
        jLabel19.setBounds(70, 220, 60, 16);

        jLabel20.setText("pro123");
        add(jLabel20);
        jLabel20.setBounds(10, 280, 40, 16);

        jLabel21.setText("pro3");
        add(jLabel21);
        jLabel21.setBounds(10, 160, 24, 16);

        jLabel22.setText("pro34");
        add(jLabel22);
        jLabel22.setBounds(10, 220, 40, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField4ActionPerformed
    {//GEN-HEADEREND:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField8ActionPerformed
    {//GEN-HEADEREND:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField12ActionPerformed
    {//GEN-HEADEREND:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField16ActionPerformed
    {//GEN-HEADEREND:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
