/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.Propiedades;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicButtonUI;
import herramientas.TextPrompt;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author jonas
 */
public class ScrollVentanas extends javax.swing.JPanel
{

    /**
     * Creates new form AltasProductos
     */
    public ScrollVentanas( JPanel jp)
    {
        initComponents();
        jScrollPane1.setViewportView(jp);
        jScrollPane1.repaint();
        JScrollBar j = jScrollPane1.getVerticalScrollBar();
        jScrollPane1.addMouseWheelListener(new MouseWheelListener()
        {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e)
            {
                int scrollAmount = e.getScrollAmount(); // Cantidad de desplazamiento por unidad de rueda
                int unitsToScroll = e.getUnitsToScroll(); // Unidades desplazadas por la rueda

                // Ajusta el valor de desplazamiento como desees. En este caso, lo duplicamos.
                int newUnitsToScroll = unitsToScroll * 8;

                // Cambia el valor del scrollbar vertical del JScrollPane
                JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
                verticalScrollBar.setValue(verticalScrollBar.getValue() + newUnitsToScroll);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 793, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
