/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pym;

import clases.conex.CRUD;
import herramientas.RoundedBorder;
import herramientas.Validaciones;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VentaProducto extends javax.swing.JPanel
{

    /**
     * Creates new form VentaProducto
     */
    LocalDate fechaA = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    // Formatear la fecha usando el formateador
    String fechaFormateada = fechaA.format(formatter);
    DefaultTableModel m1 = new DefaultTableModel();
    DefaultTableModel m2 = new DefaultTableModel();

    public VentaProducto()
    {
        initComponents();
        fecha.setText(fechaFormateada);
        menuOpc.setUI(new BasicButtonUI());
        menuOpc.setBorder(new RoundedBorder(10));
        eliminar.setUI(new BasicButtonUI());
        eliminar.setBorder(new RoundedBorder(10));
        agregar.setUI(new BasicButtonUI());
        agregar.setBorder(new RoundedBorder(10));
        cobrar.setUI(new BasicButtonUI());
        buscar.setUI(new BasicButtonUI());

        String c[] =
        {
            "ID", "Nombre", "Precio", "Cantidad", "Total"
        };
        m1.setColumnIdentifiers(c);
        jTable1.setModel(m1);
        String c2[] =
        {
            "Nombre", "Precio", "Cantidad", "Magintud", "Unidad", "Proveedor", "Categoria"
        };
        m2.setColumnIdentifiers(c2);
        jTable2.setModel(m2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        codigo = new javax.swing.JLabel();
        bienvenidos1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        menuOpc = new javax.swing.JButton();
        bienvenidos2 = new javax.swing.JLabel();
        codigoPro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        buscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        cantidad = new javax.swing.JTextField();
        codigo2 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        codigo4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalP = new javax.swing.JLabel();
        cobrar = new javax.swing.JButton();
        cobrar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        agregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        codigo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        codigo.setText("Codigo Producto");
        add(codigo);
        codigo.setBounds(50, 100, 210, 30);

        bienvenidos1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bienvenidos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenidos1.setText("Bienvenido");
        add(bienvenidos1);
        bienvenidos1.setBounds(389, 20, 230, 47);

        fecha.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        fecha.setText("jLabel1");
        add(fecha);
        fecha.setBounds(50, 40, 100, 20);

        menuOpc.setBackground(new java.awt.Color(33, 12, 255));
        menuOpc.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        menuOpc.setForeground(new java.awt.Color(255, 255, 255));
        menuOpc.setText("Menu Opciones");
        menuOpc.setBorder(null);
        menuOpc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuOpc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuOpc.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                menuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                menuOpcMouseExited(evt);
            }
        });
        menuOpc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuOpcActionPerformed(evt);
            }
        });
        add(menuOpc);
        menuOpc.setBounds(800, 20, 180, 50);

        bienvenidos2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bienvenidos2.setText("Fecha de hoy");
        add(bienvenidos2);
        bienvenidos2.setBounds(50, 20, 110, 20);

        codigoPro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        codigoPro.setToolTipText("");
        codigoPro.setBorder(null);
        codigoPro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                codigoProActionPerformed(evt);
            }
        });
        codigoPro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                codigoProKeyTyped(evt);
            }
        });
        add(codigoPro);
        codigoPro.setBounds(50, 130, 210, 30);
        add(jSeparator1);
        jSeparator1.setBounds(50, 160, 210, 10);

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoLupa.png"))); // NOI18N
        buscar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                buscarMouseExited(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarActionPerformed(evt);
            }
        });
        add(buscar);
        buscar.setBounds(280, 110, 50, 50);
        add(jSeparator3);
        jSeparator3.setBounds(50, 240, 210, 10);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidad.setToolTipText("");
        cantidad.setBorder(null);
        cantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cantidadKeyTyped(evt);
            }
        });
        add(cantidad);
        cantidad.setBounds(50, 210, 210, 30);

        codigo2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        codigo2.setText("Cantidad");
        add(codigo2);
        codigo2.setBounds(50, 180, 130, 30);

        eliminar.setBackground(new java.awt.Color(33, 12, 255));
        eliminar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.setBorder(null);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                eliminarMouseExited(evt);
            }
        });
        eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarActionPerformed(evt);
            }
        });
        add(eliminar);
        eliminar.setBounds(450, 640, 130, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Descripción", "Precio", "Cantidad", "Total"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(20, 270, 720, 340);

        jPanel1.setBackground(new java.awt.Color(33, 12, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAbastoF_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigo4.setBackground(new java.awt.Color(255, 255, 255));
        codigo4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        codigo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo4.setText("Total");
        jPanel4.add(codigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 30));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("$");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        totalP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        totalP.setText("0.0");
        jPanel5.add(totalP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));

        cobrar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        cobrar.setText("Cobrar");
        cobrar.setBorder(null);
        cobrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cobrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cobrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                cobrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                cobrarMouseExited(evt);
            }
        });
        cobrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cobrarActionPerformed(evt);
            }
        });
        jPanel1.add(cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, 40));

        cobrar1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        cobrar1.setText("Cobrar");
        cobrar1.setBorder(null);
        cobrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cobrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cobrar1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                cobrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                cobrar1MouseExited(evt);
            }
        });
        cobrar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cobrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(cobrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 70, 40));

        add(jPanel1);
        jPanel1.setBounds(750, 270, 250, 340);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        add(jPanel6);
        jPanel6.setBounds(350, 100, 620, 60);

        agregar.setBackground(new java.awt.Color(33, 12, 255));
        agregar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setBorder(null);
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                agregarMouseExited(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarActionPerformed(evt);
            }
        });
        add(agregar);
        agregar.setBounds(530, 200, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpcMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuOpcMouseEntered
    {//GEN-HEADEREND:event_menuOpcMouseEntered
        menuOpc.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_menuOpcMouseEntered

    private void menuOpcMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuOpcMouseExited
    {//GEN-HEADEREND:event_menuOpcMouseExited
        menuOpc.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_menuOpcMouseExited

    private void menuOpcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuOpcActionPerformed
    {//GEN-HEADEREND:event_menuOpcActionPerformed
        VtnPrincipal.pintar(new MenuOpciones());

    }//GEN-LAST:event_menuOpcActionPerformed

    private void codigoProActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_codigoProActionPerformed
    {//GEN-HEADEREND:event_codigoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProActionPerformed

    private void codigoProKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_codigoProKeyTyped
    {//GEN-HEADEREND:event_codigoProKeyTyped
        Validaciones.validaEntero(evt, 13, codigoPro.getText());
    }//GEN-LAST:event_codigoProKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarActionPerformed
    {//GEN-HEADEREND:event_buscarActionPerformed
        if (codigoPro.getText().isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Ingrese el codigo del producto");

        } else
        {
            actualizarTabla();
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void buscarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscarMouseEntered
    {//GEN-HEADEREND:event_buscarMouseEntered
        buscar.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buscarMouseExited
    {//GEN-HEADEREND:event_buscarMouseExited
        buscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buscarMouseExited

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cantidadActionPerformed
    {//GEN-HEADEREND:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cantidadKeyTyped
    {//GEN-HEADEREND:event_cantidadKeyTyped
        Validaciones.validaEntero(evt, 5, cantidad.getText());
    }//GEN-LAST:event_cantidadKeyTyped

    private void eliminarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminarMouseEntered
    {//GEN-HEADEREND:event_eliminarMouseEntered
        eliminar.setBackground(new Color(30, 161, 255));
    }//GEN-LAST:event_eliminarMouseEntered

    private void eliminarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_eliminarMouseExited
    {//GEN-HEADEREND:event_eliminarMouseExited
        eliminar.setBackground(new Color(33, 12, 255));
    }//GEN-LAST:event_eliminarMouseExited

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarActionPerformed
    {//GEN-HEADEREND:event_eliminarActionPerformed

        int selectedRow = jTable1.getSelectedRow(); // Obtener el índice de la fila seleccionada

        if (selectedRow != -1)
        { // Verificar si se ha seleccionado una fila
            float total = 0;
            String sentencia = "ID=" + codigoPro.getText();

            m1.removeRow(selectedRow); // Eliminar la fila del modelo de la tabla
            for (int row = 0; row < m1.getRowCount(); row++)
            {
                total += Float.parseFloat(m1.getValueAt(row, 3).toString());
            }
            totalP.setText("" + total);

        } else
        {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.");
        }


    }//GEN-LAST:event_eliminarActionPerformed

    private void cobrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cobrarMouseEntered
    {//GEN-HEADEREND:event_cobrarMouseEntered
        cobrar.setBackground(Color.DARK_GRAY);
        cobrar.setForeground(Color.white);
    }//GEN-LAST:event_cobrarMouseEntered

    private void cobrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cobrarMouseExited
    {//GEN-HEADEREND:event_cobrarMouseExited
        cobrar.setForeground(Color.black);
        cobrar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_cobrarMouseExited

    private void cobrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cobrarActionPerformed
    {//GEN-HEADEREND:event_cobrarActionPerformed
        try
        {
            String valores = "DEFAULT, '" + darFecha() + "', '" + totalP.getText() + "'";

            // Inicia una transacción
            // Inserta en la tabla ventas
            int resultadoInsercion = CRUD.create("ventas", "", valores, "ventas");
            if (resultadoInsercion == 0)
            {
                // Si la inserción en ventas es exitosa, obtenemos el nuevo ID de venta
                ResultSet resultSet = CRUD.read("ventas", "MAX(id)", "");
                resultSet.next();
                int nuevoIdVenta = resultSet.getInt(1);

                // Iteramos sobre los productos para insertar en venta_producto
                for (int i = 0; i < m1.getRowCount(); i++)
                {
                    ResultSet idPro = CRUD.read("producto", "*", "where nombre = '" + m1.getValueAt(i, 1).toString() + "'");
                    idPro.next();
                    valores = "'" + idPro.getString("id") + "', '" + nuevoIdVenta + "', '"
                            + m1.getValueAt(i, 3).toString() + "','" + m1.getValueAt(i, 4).toString() + "'";
                    // Actualiza el stock de los productos
                    CRUD.updateStonksVenta("nombre = '" + m1.getValueAt(i, 1).toString() + "'", Integer.parseInt(m1.getValueAt(i, 3).toString()));
                    // Inserta en venta_producto
                    CRUD.create("venta_producto", "", valores, "venta_producto");
                }

                JOptionPane.showMessageDialog(null, "La compra fue exitosa");
                m1.setRowCount(0);
                m2.setRowCount(0);
                codigoPro.setText("");
                cantidad.setText("");
                totalP.setText("0.0");
            } else
            {

                JOptionPane.showMessageDialog(null, "Error desconocido \n" + "Contactar con Soporte");
            }

        } catch (Exception e)
        {
            // Manejo de errores
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_cobrarActionPerformed

    private void cobrar1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cobrar1MouseEntered
    {//GEN-HEADEREND:event_cobrar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrar1MouseEntered

    private void cobrar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cobrar1MouseExited
    {//GEN-HEADEREND:event_cobrar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrar1MouseExited

    private void cobrar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cobrar1ActionPerformed
    {//GEN-HEADEREND:event_cobrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrar1ActionPerformed

    private void agregarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarMouseEntered
    {//GEN-HEADEREND:event_agregarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_agregarMouseExited
    {//GEN-HEADEREND:event_agregarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarMouseExited

    private void agregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarActionPerformed
    {//GEN-HEADEREND:event_agregarActionPerformed
        if (codigoPro.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el código del producto");
        } else
        {
            if (cantidad.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida");
            } else
            {
                int cantidadInt = 0;
                try
                {
                    cantidadInt = Integer.parseInt(cantidad.getText());
                } catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido");
                    return;
                }

                if (cantidadInt < 1)
                {
                    JOptionPane.showMessageDialog(this, "Ingrese una cantidad mayor a 0");
                } else
                {
                    try
                    {
                        float total = 0;
                        String sentencia = "id = " + codigoPro.getText();

                        ResultSet rat2 = CRUD.read("producto", "*", "WHERE ID =" + codigoPro.getText());
                        if (!rat2.next())
                        {
                            JOptionPane.showMessageDialog(this, "El producto no existe");
                            return;
                        }
                        int cantidadDisponible = rat2.getInt("cantidad");

                        // Calcular la cantidad total que se intentará agregar a la tabla
                        int cantidadTotalEnTabla = cantidadInt;
                        for (int i = 0; i < m1.getRowCount(); i++)
                        {
                            if (codigoPro.getText().equals(m1.getValueAt(i, 0)))
                            {
                                cantidadTotalEnTabla += Integer.parseInt(m1.getValueAt(i, 3).toString());
                            }
                        }

                        if (cantidadTotalEnTabla >= cantidadDisponible)
                        {
                            JOptionPane.showMessageDialog(this, "La cantidad total en la tabla excede las existencias disponibles para el producto " + rat2.getString("nombre"));
                        } else
                        {
                            ResultSet rat = CRUD.read("producto", "id, nombre, precio", "WHERE ID =" + codigoPro.getText());
                            if (!rat.next())
                            {
                                JOptionPane.showMessageDialog(this, "El producto no existe");
                                return;
                            }

                            boolean productoExiste = false;
                            for (int i = 0; i < m1.getRowCount(); i++)
                            {
                                if (codigoPro.getText().equals(m1.getValueAt(i, 0)))
                                {
                                    int nuevaCantidad = Integer.parseInt(m1.getValueAt(i, 3).toString()) + cantidadInt;
                                    m1.setValueAt(nuevaCantidad, i, 3);
                                    m1.setValueAt(nuevaCantidad * rat.getFloat("precio"), i, 4);
                                    productoExiste = true;
                                    break;
                                }
                            }

                            if (!productoExiste)
                            {
                                String[] f =
                                {
                                    rat.getString("id"),
                                    rat.getString("nombre"),
                                    rat.getString("precio"),
                                    cantidad.getText(),
                                    String.valueOf(cantidadInt * rat.getFloat("precio"))
                                };
                                m1.addRow(f);
                            }

                            for (int row = 0; row < m1.getRowCount(); row++)
                            {
                                total += Float.parseFloat(m1.getValueAt(row, 4).toString());
                            }
                            totalP.setText("" + total);
                        }

                    } catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.toString());
                        System.out.println(e.toString());
                    }
                }
            }
        }


    }//GEN-LAST:event_agregarActionPerformed

    public void actualizarTabla()
    {

        jTable2.setRowHeight(32);
        m2 = new DefaultTableModel();
        String c2[] =
        {
            "Nombre", "Precio", "Cantidad", "Magintud", "Unidad", "Proveedor", "Categoria"
        };
        m2.setColumnIdentifiers(c2);
        jTable2.setModel(m2);
        try
        {
            ResultSet rat = CRUD.read("producto", "*", "WHERE ID =" + codigoPro.getText());
            if (rat.next())
            {

                ResultSet ratProv = CRUD.read("proveedor", "*", "WHERE id = " + rat.getString("id_Proveedor"));
                ratProv.next();
                ResultSet ratCat = CRUD.read("categoria", "*", "WHERE id = " + rat.getString("id_Categoria"));
                ratCat.next();
                String f[] =
                {
                    rat.getString("nombre"), rat.getString("precio"), rat.getString("cantidad"), rat.getString("magnitudMed"),
                    rat.getString("unidadMed"), ratProv.getString("nombre"),
                    ratCat.getString("nombre")
                };
                m2.addRow(f);
            } else
            {
                JOptionPane.showMessageDialog(this, "Ingrese un id existente");
            }

        } catch (Exception e)
        {
            System.out.println("asdasaaaaaaaaaaaaa");
        }
    }

    public String darFecha()
    {
        Date fechaHora = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd ");
        String s = dateFormat.format(fechaHora);
        System.out.println(s);
        return s;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel bienvenidos1;
    private javax.swing.JLabel bienvenidos2;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton cobrar;
    private javax.swing.JButton cobrar1;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo2;
    private javax.swing.JLabel codigo4;
    private javax.swing.JTextField codigoPro;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton menuOpc;
    private javax.swing.JLabel totalP;
    // End of variables declaration//GEN-END:variables
}
